LARRY_GAME: PhysicsWorld Class Reference
PhysicsWorld Class Reference
This manages coin creation and collisions of the coins.
#include <PhysicsWorld.h>
Classes
struct Body
Public Member Functions
PhysicsWorld (bool _debug)
ctor
~PhysicsWorld ()
dtor
void setGravity (float _x, float _y, float _z)
set the gravity for the whole world
void setGravity (ngl::Vec3 _g)
unsigned int getNumCollisionObjects () const
returns the number of collision objects in the world
std::string getBodyNameAtIndex (unsigned int i) const
returns the name of the body at the chosen index
void addSphere (std::string _shapeName, const ngl::Vec3 &_pos, ngl::Real _mass, const ngl::Vec3 &_inertia, bool _draw)
adds a rigid body sphere to the physics world
void addLegSphere (std::string _shapeName, const ngl::Vec3 &_pos, ngl::Real _mass, const ngl::Vec3 &_inertia)
adds a rigid body capsule to the physics world, used for standing character
void addMesh (std::string _shapeName, const ngl::Vec3 &_pos, ngl::Real _mass, const ngl::Vec3 &_inertia)
adds a rigid body mesh to the physics world
void addLevelMesh (std::string _shapeName, const ngl::Vec3 &_pos)
adds an unmoving rigid body mesh to the physics world. Creates a convex collision shape.
void addBox (std::string _shapeName, const ngl::Vec3 &_pos)
adds a rigid body cube to the physics world
void step (float _timeStep, float _maxSubSteps, float _fixedTimeStep)
steps through the physics simulation
void addPlatform (std::string _shapeName, const ngl::Vec3 &_pos, ngl::Real _mass, const ngl::Vec3 &_inertia)
adds a rigid body platform mesh to the physics world. These don't collide with level meshes.
void addImpulse (const ngl::Vec3 &_i, std::string _shape)
adds an impulse force to the shape
void applyForceCentral (const ngl::Vec3 &_p, std::string _shape)
applies a force to the shape
ngl::Vec3 getLinVelocity (std::string _shape)
returns the linear velocity of the specified shape
void setLinVelocity (std::string _shape, ngl::Vec3 &_velocity)
sets the linear velocity of the specified shape
ngl::Vec3 getAngVelocity (std::string _shape)
returns the angular velocity of the specified shape
void setAngVelocity (std::string _shape, ngl::Vec3 &_velocity)
sets the angular velocity of the specified shape
void reset ()
removes all physics bodies
ngl::Vec3 getPosition (std::string _shape)
returns the position of the specified shape
ngl::Mat4 getTransformMatrix (unsigned int _index)
returns the transformation matrix of the specified shape
ngl::Mat4 getTransformMatrix (std::string _shape)
returns the transformation matrix of the specified shape
void setTransformMatrix (std::string _shape, ngl::Mat4 _mat)
sets the transformation matrix of the specified shape
void printBodies ()
prints the names of all rigid bodies in the world
void removeCollisionObj (std::string _shape)
removes the specified rigid body from the world
ngl::Vec3 getCentreOfMass (std::string _shape)
returns the position of the specified shape's centre of mass
void debugWorldDraw ()
draws all the collision shapes as wireframes
bool rayTest (const ngl::Vec3 &_a, const ngl::Vec3 &_b)
fires a ray from a to b and returns true if a collision object is obstructing it
bool rayTest (const ngl::Vec3 &_a, const ngl::Vec3 &_b, ngl::Vec3 &_out)
ngl::Vec3 getVelocityOfPlatform (const ngl::Vec3 &_a, const ngl::Vec3 &_b)
fires a ray from a to b and returns the velocity of the object it hits
ngl::Vec3 rayNormalTest (const ngl::Vec3 &_a, const ngl::Vec3 &_b)
fires a ray from a to b and returns the normal of the object at the hit point
void setGravityForBody (std::string _shape, ngl::Vec3 _vec)
sets the gravity multiplier for a specific body (useful for making things weightless)
void freezeBody (std::string _shape)
stops all motion for the specified body
btRigidBody * FindGameObject (btRigidBody *_shape)
function checks whether specific shape is in m_bodies. If true it is added to m_collisionBodies
Private Types
typedef std::pair< const
btRigidBody *, const
btRigidBody * > collisionPair
typedef std::set< collisionPair > collisionPairs
Private Attributes
std::unique_ptr< BulletDebugDraw > debugDrawer
the debug drawer
std::unique_ptr
< btDefaultCollisionConfiguration > m_collisionConfiguration
std::unique_ptr
< btCollisionDispatcher > m_dispatcher
std::unique_ptr
< btBroadphaseInterface > m_overlappingPairCache
std::unique_ptr
< btSequentialImpulseConstraintSolver > m_solver
std::unique_ptr
< btDiscreteDynamicsWorld > m_dynamicsWorld
btCollisionShape * m_groundShape
std::vector< Body > m_bodies
Body collisionPairA
Body collisionPairB
std::vector< Body > m_collisionBodies
std::vector< std::vector< Body > > m_collisionBodiesPair
std::vector< Body > m_findGameBodies
collisionPairs m_pairsLastUpdate
Detailed Description
This manages coin creation and collisions of the coins.
Definition at line 18 of file PhysicsWorld.h.
Member Typedef Documentation
typedef std::pair<const btRigidBody*, const btRigidBody*> PhysicsWorld::collisionPair private
Definition at line 245 of file PhysicsWorld.h.
typedef std::set<collisionPair> PhysicsWorld::collisionPairs private
Definition at line 246 of file PhysicsWorld.h.
Constructor & Destructor Documentation
PhysicsWorld::PhysicsWorld (bool _debug)
ctor
Parameters
[in] _debug - enables or disables debug drawing
collision configuration contains default setup for memory, collision setup. Advanced users can create their own configuration.
use the default collision dispatcher. For parallel processing you can use a diffent dispatcher (see Extras/BulletMultiThreaded)
btDbvtBroadphase is a good general purpose broadphase. You can also try out btAxis3Sweep.
the default constraint solver. For parallel processing you can use a different solver (see Extras/BulletMultiThreaded)
Definition at line 17 of file PhysicsWorld.cpp.
References debugDrawer, m_collisionConfiguration, m_dispatcher, m_dynamicsWorld, m_overlappingPairCache, and m_solver.
PhysicsWorld::~PhysicsWorld ()
dtor
Definition at line 222 of file PhysicsWorld.cpp.
Member Function Documentation
void PhysicsWorld::addBox (std::string _shapeName, const ngl::Vec3 & _pos)
adds a rigid body cube to the physics world
Parameters
[in] _shapeName - the name of the shape
[in] _pos - the shape's position
Create Dynamic Objects
Definition at line 185 of file PhysicsWorld.cpp.
References PhysicsWorld::Body::body, COL_BALL, COL_ENVI, COL_MESH, CollisionShape::getShape(), CollisionShape::instance(), m_bodies, m_dynamicsWorld, and PhysicsWorld::Body::name.
void PhysicsWorld::addImpulse (const ngl::Vec3 & _i, std::string _shape)
adds an impulse force to the shape
Parameters
[in] _i - the vector for the force
[in] _shape - the name of the shape to apply the force to
Definition at line 510 of file PhysicsWorld.cpp.
References m_bodies.
void PhysicsWorld::addLegSphere (std::string _shapeName, const ngl::Vec3 & _pos, ngl::Real _mass, const ngl::Vec3 & _inertia)
adds a rigid body capsule to the physics world, used for standing character
Parameters
[in] _shapeName - the name of the shape
[in] _pos - the shape's position
[in] _mass - the mass of the shape
[in] _inertia - the local inertia for the shape
Create Dynamic Objects
Definition at line 88 of file PhysicsWorld.cpp.
References PhysicsWorld::Body::body, COL_BALL, COL_ENVI, CollisionShape::getShape(), CollisionShape::instance(), m_bodies, m_dynamicsWorld, and PhysicsWorld::Body::name.
void PhysicsWorld::addLevelMesh (std::string _shapeName, const ngl::Vec3 & _pos)
adds an unmoving rigid body mesh to the physics world. Creates a convex collision shape.
Parameters
[in] _shapeName - the name of the shape, must match the name of an existing collision shape
[in] _pos - the shape's position
Create Dynamic Objects
Definition at line 128 of file PhysicsWorld.cpp.
References PhysicsWorld::Body::body, COL_BALL, COL_ENVI, COL_MESH, CollisionShape::getShape(), CollisionShape::instance(), m_bodies, m_dynamicsWorld, and PhysicsWorld::Body::name.
void PhysicsWorld::addMesh (std::string _shapeName, const ngl::Vec3 & _pos, ngl::Real _mass, const ngl::Vec3 & _inertia)
adds a rigid body mesh to the physics world
Parameters
[in] _shapeName - the name of the shape, must match the name of an existing collision shape
[in] _pos - the shape's position
[in] _mass - the mass of the shape
[in] _inertia - the local inertia for the shape
Create Dynamic Objects
Definition at line 154 of file PhysicsWorld.cpp.
References PhysicsWorld::Body::body, COL_ENVI, COL_MESH, CollisionShape::getShape(), CollisionShape::instance(), m_bodies, m_dynamicsWorld, and PhysicsWorld::Body::name.
void PhysicsWorld::addPlatform (std::string _shapeName, const ngl::Vec3 & _pos, ngl::Real _mass, const ngl::Vec3 & _inertia)
adds a rigid body platform mesh to the physics world. These don't collide with level meshes.
Parameters
[in] _shapeName - the name of the shape, must match the name of an existing collision shape
[in] _pos - the shape's position
[in] _mass - the mass of the shape
[in] _inertia - the local inertia for the shape
Create Dynamic Objects
Definition at line 227 of file PhysicsWorld.cpp.
References PhysicsWorld::Body::body, COL_BALL, COL_ENVI, COL_MESH, CollisionShape::getShape(), CollisionShape::instance(), m_bodies, m_dynamicsWorld, and PhysicsWorld::Body::name.
void PhysicsWorld::addSphere (std::string _shapeName, const ngl::Vec3 & _pos, ngl::Real _mass, const ngl::Vec3 & _inertia, bool _draw)
adds a rigid body sphere to the physics world
Parameters
[in] _shapeName - the name of the shape
[in] _pos - the shape's position
[in] _mass - the mass of the shape
[in] _inertia - the local inertia for the shape
[in] _draw - enables drawing of the collision mesh in debug mode
Create Dynamic Objects
Definition at line 47 of file PhysicsWorld.cpp.
References PhysicsWorld::Body::body, COL_BALL, COL_ENVI, CollisionShape::getShape(), CollisionShape::instance(), m_bodies, m_dynamicsWorld, and PhysicsWorld::Body::name.
void PhysicsWorld::applyForceCentral (const ngl::Vec3 & _p, std::string _shape)
applies a force to the shape
Parameters
[in] _p - the vector for the force
[in] _shape - the name of the shape to apply the force to
Definition at line 527 of file PhysicsWorld.cpp.
References m_bodies.
void PhysicsWorld::debugWorldDraw ()
draws all the collision shapes as wireframes
Definition at line 574 of file PhysicsWorld.cpp.
References debugDrawer, and m_dynamicsWorld.
btRigidBody * PhysicsWorld::FindGameObject (btRigidBody * _shape)
function checks whether specific shape is in m_bodies. If true it is added to m_collisionBodies
Parameters
[in] _shape - the name of the shape to find
Definition at line 692 of file PhysicsWorld.cpp.
References m_bodies, and m_collisionBodies.
void PhysicsWorld::freezeBody (std::string _shape)
stops all motion for the specified body
Parameters
[in] _shape - the name of the shape to use
Definition at line 673 of file PhysicsWorld.cpp.
References m_bodies.
ngl::Vec3 PhysicsWorld::getAngVelocity (std::string _shape)
returns the angular velocity of the specified shape
Parameters
[in] _shape - the name of the shape to use
Definition at line 436 of file PhysicsWorld.cpp.
References m_bodies.
std::string PhysicsWorld::getBodyNameAtIndex (unsigned int i) const inline
returns the name of the body at the chosen index
Parameters
[in] i - the index of the desired body
Definition at line 56 of file PhysicsWorld.h.
References m_bodies.
ngl::Vec3 PhysicsWorld::getCentreOfMass (std::string _shape)
returns the position of the specified shape's centre of mass
Parameters
[in] _shape - the name of the shape to use
Definition at line 541 of file PhysicsWorld.cpp.
References m_bodies.
ngl::Vec3 PhysicsWorld::getLinVelocity (std::string _shape)
returns the linear velocity of the specified shape
Parameters
[in] _shape - the name of the shape to use
Definition at line 379 of file PhysicsWorld.cpp.
References m_bodies.
unsigned int PhysicsWorld::getNumCollisionObjects () const inline
returns the number of collision objects in the world
Definition at line 48 of file PhysicsWorld.h.
References m_dynamicsWorld.
ngl::Vec3 PhysicsWorld::getPosition (std::string _shape)
returns the position of the specified shape
Parameters
[in] _shape - the name of the shape to use
Definition at line 350 of file PhysicsWorld.cpp.
References m_bodies.
ngl::Mat4 PhysicsWorld::getTransformMatrix (unsigned int _index)
returns the transformation matrix of the specified shape
Parameters
[in] _index - the index of the desired shape in the bodies array
Definition at line 270 of file PhysicsWorld.cpp.
References m_bodies.
ngl::Mat4 PhysicsWorld::getTransformMatrix (std::string _shape)
returns the transformation matrix of the specified shape
Parameters
[in] _shape - the name of the shape to use
Definition at line 288 of file PhysicsWorld.cpp.
References m_bodies.
ngl::Vec3 PhysicsWorld::getVelocityOfPlatform (const ngl::Vec3 & _a, const ngl::Vec3 & _b)
fires a ray from a to b and returns the velocity of the object it hits
Parameters
[in] _a - the origin point
[in] _b - the target point
Definition at line 602 of file PhysicsWorld.cpp.
References getLinVelocity(), m_bodies, and m_dynamicsWorld.
void PhysicsWorld::printBodies ()
prints the names of all rigid bodies in the world
Definition at line 502 of file PhysicsWorld.cpp.
References m_bodies.
ngl::Vec3 PhysicsWorld::rayNormalTest (const ngl::Vec3 & _a, const ngl::Vec3 & _b)
fires a ray from a to b and returns the normal of the object at the hit point
Parameters
[in] _a - the origin point
[in] _b - the target point
Definition at line 710 of file PhysicsWorld.cpp.
References m_dynamicsWorld.
bool PhysicsWorld::rayTest (const ngl::Vec3 & _a, const ngl::Vec3 & _b)
fires a ray from a to b and returns true if a collision object is obstructing it
Parameters
[in] _a - the origin point
[in] _b - the target point
[in] _out - the position of the impact point
Definition at line 580 of file PhysicsWorld.cpp.
References m_dynamicsWorld.
bool PhysicsWorld::rayTest (const ngl::Vec3 & _a, const ngl::Vec3 & _b, ngl::Vec3 & _out)
Definition at line 635 of file PhysicsWorld.cpp.
References m_dynamicsWorld.
void PhysicsWorld::removeCollisionObj (std::string _shape)
removes the specified rigid body from the world
Parameters
[in] _shape - the name of the shape to remove
Definition at line 560 of file PhysicsWorld.cpp.
References m_bodies, and m_dynamicsWorld.
void PhysicsWorld::reset ()
removes all physics bodies
Definition at line 492 of file PhysicsWorld.cpp.
References m_bodies, and m_dynamicsWorld.
void PhysicsWorld::setAngVelocity (std::string _shape, ngl::Vec3 & _velocity)
sets the angular velocity of the specified shape
Parameters
[in] _shape - the name of the shape to use
[in] _velocity - the new velocity vector
Definition at line 411 of file PhysicsWorld.cpp.
References m_bodies.
void PhysicsWorld::setGravity (float _x, float _y, float _z) inline
set the gravity for the whole world
Parameters
[in] _x
[in] _y
[in] _z
[in] _g - single vector for gravity
Definition at line 37 of file PhysicsWorld.h.
References m_dynamicsWorld.
void PhysicsWorld::setGravity (ngl::Vec3 _g) inline
Definition at line 41 of file PhysicsWorld.h.
References m_dynamicsWorld.
void PhysicsWorld::setGravityForBody (std::string _shape, ngl::Vec3 _vec)
sets the gravity multiplier for a specific body (useful for making things weightless)
Parameters
[in] _shape - the name of the shape to use
[in] _vec - the new gravity vector to use
Definition at line 658 of file PhysicsWorld.cpp.
References m_bodies.
void PhysicsWorld::setLinVelocity (std::string _shape, ngl::Vec3 & _velocity)
sets the linear velocity of the specified shape
Parameters
[in] _shape - the name of the shape to use
[in] _velocity - the new velocity vector
Definition at line 466 of file PhysicsWorld.cpp.
References m_bodies.
void PhysicsWorld::setTransformMatrix (std::string _shape, ngl::Mat4 _mat)
sets the transformation matrix of the specified shape
Parameters
[in] _shape - the name of the shape to use
[in] _mat - the new matrix
Definition at line 323 of file PhysicsWorld.cpp.
References m_bodies.
void PhysicsWorld::step (float _timeStep, float _maxSubSteps, float _fixedTimeStep)
steps through the physics simulation
Parameters
[in] _timeStep - time between two physics updates
[in] _maxSubSteps - the maximum number of steps Bullet may use each time this function is called
[in] _fixedTimeStep - the maximum size of a step
Definition at line 264 of file PhysicsWorld.cpp.
References m_dynamicsWorld.
Member Data Documentation
Body PhysicsWorld::collisionPairA private
Definition at line 247 of file PhysicsWorld.h.
Body PhysicsWorld::collisionPairB private
Definition at line 248 of file PhysicsWorld.h.
std::unique_ptr<BulletDebugDraw> PhysicsWorld::debugDrawer private
the debug drawer
Definition at line 233 of file PhysicsWorld.h.
std::vector<Body> PhysicsWorld::m_bodies private
Definition at line 242 of file PhysicsWorld.h.
std::vector<Body> PhysicsWorld::m_collisionBodies private
Definition at line 249 of file PhysicsWorld.h.
std::vector<std::vector <Body> > PhysicsWorld::m_collisionBodiesPair private
Definition at line 250 of file PhysicsWorld.h.
std::unique_ptr<btDefaultCollisionConfiguration> PhysicsWorld::m_collisionConfiguration private
Definition at line 236 of file PhysicsWorld.h.
std::unique_ptr<btCollisionDispatcher> PhysicsWorld::m_dispatcher private
Definition at line 237 of file PhysicsWorld.h.
std::unique_ptr<btDiscreteDynamicsWorld> PhysicsWorld::m_dynamicsWorld private
Definition at line 240 of file PhysicsWorld.h.
std::vector<Body> PhysicsWorld::m_findGameBodies private
Definition at line 251 of file PhysicsWorld.h.
btCollisionShape* PhysicsWorld::m_groundShape private
Definition at line 241 of file PhysicsWorld.h.
std::unique_ptr<btBroadphaseInterface> PhysicsWorld::m_overlappingPairCache private
Definition at line 238 of file PhysicsWorld.h.
collisionPairs PhysicsWorld::m_pairsLastUpdate private
Definition at line 252 of file PhysicsWorld.h.
std::unique_ptr<btSequentialImpulseConstraintSolver> PhysicsWorld::m_solver private
Definition at line 239 of file PhysicsWorld.h.
The documentation for this class was generated from the following files:
PhysicsWorld.h
PhysicsWorld.cpp