LARRY_GAME: Controls Class Reference
Controls Class Reference
A wrapper class for all of the controls for the character of the game.
#include <Controls.h>
Public Member Functions
Controls (PhysicsWorld *_physics, Character *_character)
ctor for Controls class
void setMassPositive ()
increments the mass of the object
void setMassNegative ()
decrements the mass of the object
void setMaxVelPositive ()
increments the max velocity of the object
void setMaxVelNegative ()
decrements the max velocity of the object
void setMultiplierPositive ()
increments the multiplier for velocity of the object
void setMultiplierNegative ()
decrements the multiplier for velocity of the object
void jumpImpulse ()
applies a jump impulse to the character
void stopJumpHopTimer ()
stops the jump hop timer
void startJumpHopTimer ()
starts the jump hop timer
void godMode ()
disables gravity (cheat mode, shapeshift to re-enable gravity)
void shapeshift ()
shapeshifts the character into a ball/ball with legs
void characterMovement (ngl::Vec3 &_move)
moves the character based on the direction vector
void setJumpForcePositive ()
increments the jump force value
void setJumpForceNegative ()
decrements the jump force value
void setJumpHopMaxTimePositive ()
increments the max jump time
void setJumpHopMaxTimeNegative ()
decrements the max jump time
void setFrictionPositive ()
increments the characters friction
void setFrictionNegative ()
decrements the characters friction
float getMass ()
returns the mass of the character
float getMaxVelocity ()
returns the max velocity of the character
float getMultiplier ()
returns the multiplier value of the character
float getFriction ()
returns the friction value
float getJumpForce ()
returns the jump force
float getJumpHopTime ()
returns the jump hop time
int getJumpHopMaxTime ()
returns the maximum hop time
Private Attributes
PhysicsWorld * m_physics
a pointer used to hold the physics world pointer to acces the physics world of the game
Character * m_character
a pointer used to hold the character
Detailed Description
A wrapper class for all of the controls for the character of the game.
Definition at line 13 of file Controls.h.
Constructor & Destructor Documentation
Controls::Controls (PhysicsWorld * _physics, Character * _character)
ctor for Controls class
Parameters
[in] _physics A pointer to the game physics world
Definition at line 3 of file Controls.cpp.
References m_character, and m_physics.
Member Function Documentation
void Controls::characterMovement (ngl::Vec3 & _move)
moves the character based on the direction vector
Parameters
[in] _move the direction vector for the character
Definition at line 61 of file Controls.cpp.
References Character::characterMove(), and m_character.
float Controls::getFriction ()
returns the friction value
Definition at line 126 of file Controls.cpp.
References Character::getFriction(), and m_character.
float Controls::getJumpForce ()
returns the jump force
Definition at line 106 of file Controls.cpp.
References Character::getJumpForce(), and m_character.
int Controls::getJumpHopMaxTime ()
returns the maximum hop time
Definition at line 111 of file Controls.cpp.
References Character::getJumpHopMaxTime(), and m_character.
float Controls::getJumpHopTime ()
returns the jump hop time
Definition at line 131 of file Controls.cpp.
References Character::getJumpHopTime(), and m_character.
float Controls::getMass ()
returns the mass of the character
Definition at line 66 of file Controls.cpp.
References Character::getMass(), and m_character.
float Controls::getMaxVelocity ()
returns the max velocity of the character
Definition at line 71 of file Controls.cpp.
References Character::getMaxVelocity(), and m_character.
float Controls::getMultiplier ()
returns the multiplier value of the character
Definition at line 76 of file Controls.cpp.
References Character::getMultiplier(), and m_character.
void Controls::godMode ()
disables gravity (cheat mode, shapeshift to re-enable gravity)
Definition at line 26 of file Controls.cpp.
References Character::godMode(), and m_character.
void Controls::jumpImpulse ()
applies a jump impulse to the character
Definition at line 11 of file Controls.cpp.
References Character::jumpImpulse(), and m_character.
void Controls::setFrictionNegative ()
decrements the characters friction
Definition at line 121 of file Controls.cpp.
References m_character, and Character::setFrictionNegative().
void Controls::setFrictionPositive ()
increments the characters friction
Definition at line 116 of file Controls.cpp.
References m_character, and Character::setFrictionPositive().
void Controls::setJumpForceNegative ()
decrements the jump force value
Definition at line 91 of file Controls.cpp.
References m_character, and Character::setJumpForceNegative().
void Controls::setJumpForcePositive ()
increments the jump force value
Definition at line 86 of file Controls.cpp.
References m_character, and Character::setJumpForcePositive().
void Controls::setJumpHopMaxTimeNegative ()
decrements the max jump time
Definition at line 101 of file Controls.cpp.
References m_character, and Character::setJumpHopMaxTimeNegative().
void Controls::setJumpHopMaxTimePositive ()
increments the max jump time
Definition at line 96 of file Controls.cpp.
References m_character, and Character::setJumpHopMaxTimePositive().
void Controls::setMassNegative ()
decrements the mass of the object
Definition at line 36 of file Controls.cpp.
References m_character, and Character::setMassNegative().
void Controls::setMassPositive ()
increments the mass of the object
Definition at line 31 of file Controls.cpp.
References m_character, and Character::setMassPositive().
void Controls::setMaxVelNegative ()
decrements the max velocity of the object
Definition at line 46 of file Controls.cpp.
References m_character, and Character::setMaxVelNegative().
void Controls::setMaxVelPositive ()
increments the max velocity of the object
Definition at line 41 of file Controls.cpp.
References m_character, and Character::setMaxVelPositive().
void Controls::setMultiplierNegative ()
decrements the multiplier for velocity of the object
Definition at line 56 of file Controls.cpp.
References m_character, and Character::setMultiplierNegative().
void Controls::setMultiplierPositive ()
increments the multiplier for velocity of the object
Definition at line 51 of file Controls.cpp.
References m_character, and Character::setMultiplierPositive().
void Controls::shapeshift ()
shapeshifts the character into a ball/ball with legs
Definition at line 81 of file Controls.cpp.
References m_character, and Character::shapeshift().
void Controls::startJumpHopTimer ()
starts the jump hop timer
Definition at line 21 of file Controls.cpp.
References m_character, and Character::startJumpHopTimer().
void Controls::stopJumpHopTimer ()
stops the jump hop timer
Definition at line 16 of file Controls.cpp.
References m_character, and Character::stopJumpHopTimer().
Member Data Documentation
Character* Controls::m_character private
a pointer used to hold the character
Definition at line 130 of file Controls.h.
PhysicsWorld* Controls::m_physics private
a pointer used to hold the physics world pointer to acces the physics world of the game
Definition at line 126 of file Controls.h.
The documentation for this class was generated from the following files:
Controls.h
Controls.cpp