LARRY_GAME: NGLDraw Class Reference
NGLDraw Class Reference
This manages coin creation and collisions of the coins.
#include <NGLDraw.h>
Public Member Functions
NGLDraw ()
ctor this will have a valid OpenGL context so we can create gl stuff
~NGLDraw ()
dtor used to remove any NGL stuff created
void resize (int _w, int _h)
resize our screen and set the camera aspect ratio
void draw ()
draw the scene
void drawDepth ()
draw the scene from the lights POV for the depth pass
void mouseMoveEvent (const SDL_MouseMotionEvent &_event)
this method is called every time a mouse is moved
void mousePressEvent (const SDL_MouseButtonEvent &_event)
this method is called every time a mouse button is presses
void mouseReleaseEvent (const SDL_MouseButtonEvent &_event)
this method is called everytime the mouse button is released
void wheelEvent (const SDL_MouseWheelEvent &_event)
this method is called everytime the mouse wheel is moved
void updateRot ()
void addCube ()
adds a cube used to test bullet physics
void updateDraw ()
void updateDebugDraw ()
void updatePhysics (float time)
void debugPhysicsWorld (bool _value)
void checkpoints ()
void makeNoise (float m_freq, float m_scale)
method to create a noise texture
void shaderType (std::string _shaderName, ngl::Vec3 _shaderColour, bool stripe, float shine, ngl::Transformation &_trans)
method to pick a shader type and load object matrices to the shader
void setGravityFactorPositive ()
increments the gravity factor
void setGravityFactorNegative ()
decrements the gravity factor
float getGravityFactor ()
get the value that multiplies with -9.8 to create the gravity
void restartGame ()
resets the character and game values
PhysicsWorld * getPhysicsWorld ()
returns a pointer to the PhysicsWorld
Character * getCharacter ()
returns a pointer to the character
Level * getLevel ()
returns a pointer to the level manager
Animation * getAnimation ()
returns a pointer to the animation manager
CoinFactory * getCoinFactory ()
returns a pointer to the coin factory
PlatformFactory * getPlatformFactory ()
returns a pointer to the platform factory
int increaseShaderTime ()
increments the variable m_time
void createFramebufferObject ()
create our fbo for shadows
float increaseLowThreshold ()
increment the lowThresholdKey for the disintegration effect
void resetLowThreshold ()
reset the lowThresholdKey to zero
void restartGameValues ()
reset the game values
float increaseCoinColour ()
reset the game values
void resetCoinColour ()
reset coin color to zero
Private Member Functions
void loadMatricesToShader (ngl::Transformation &_trans)
method to load transform data to the shaders
Private Attributes
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
bool m_rotate
flag to indicate if the mouse button is pressed when dragging
float m_origX
the previous x mouse value
float m_origY
the previous y mouse value
int m_origXPos
the previous x mouse value for Position changes
int m_origYPos
the previous y mouse value for Position changes
ngl::Mat4 m_mouseGlobalTX
used to store the global mouse transforms
Camera * m_cam
Our Camera.
ngl::Vec3 m_modelPos
the model position for mouse movement
ngl::Light * m_light
a simple light use to illuminate the screen
std::unique_ptr< PhysicsWorld > m_physics
the PhysicsWorld from bullet physics
std::unique_ptr< HighScore > m_highScore
class to manage the high score
std::unique_ptr< TriggerFactory > m_triggerFactory
class to manage the trigger volumes
std::unique_ptr< Character > m_character
class to manage the character
std::unique_ptr< Level > m_level
class to manage all the level meshes
std::unique_ptr< Animation > m_animation
class to handle all the animation
std::unique_ptr< CoinFactory > m_coinFactory
class to manage the coins
std::unique_ptr< PlatformFactory > m_platformFactory
class to manage all the platforms
std::unique_ptr< Text > m_text
text object
std::unique_ptr< Text > m_textHighscore
text object
std::unique_ptr< ngl::Obj > m_larryMesh
mesh for the character
std::unique_ptr< ngl::Obj > m_level1Mesh
level mesh
std::unique_ptr< ngl::Obj > m_level2_1Mesh
level mesh
std::unique_ptr< ngl::Obj > m_level2_2Mesh
level mesh
std::unique_ptr< ngl::Obj > m_level2_3aMesh
level mesh
std::unique_ptr< ngl::Obj > m_level2_3bMesh
level mesh
std::unique_ptr< ngl::Obj > m_level3Mesh
level mesh
std::unique_ptr< ngl::Obj > m_level4_1Mesh
level mesh
std::unique_ptr< ngl::Obj > m_level4_2Mesh
level mesh
std::unique_ptr< ngl::Obj > m_level5Mesh
level mesh
std::unique_ptr< ngl::Obj > m_coinMesh
coin mesh
std::unique_ptr< ngl::Obj > m_platformMesh_platform
platform mesh
std::unique_ptr< ngl::Obj > m_platformMesh_bouncePad
platform mesh
std::unique_ptr< ngl::Obj > m_platformMesh_barrier01
platform mesh
std::unique_ptr< ngl::Obj > m_level2Platform
platform mesh
std::unique_ptr< ngl::Obj > m_level2Sliding1
platform mesh
std::unique_ptr< ngl::Obj > m_level2Sliding2
platform mesh
std::unique_ptr< ngl::Obj > m_level4Bridge1Mesh
platform mesh
std::unique_ptr< ngl::Obj > m_level4Bridge2Mesh
platform mesh
std::unique_ptr< ngl::Obj > m_level4RotPlatformMesh
platform mesh
std::unique_ptr< ngl::Obj > m_level5MovingPlat
platform mesh
std::unique_ptr< ngl::Obj > m_level1_bouncePlatformMesh
platform mesh
std::unique_ptr< ngl::Obj > m_level5Stick
level 5 mesh
std::unique_ptr< ngl::Obj > m_finish
finish mesh
ngl::Mat4 m_bodyTransform
transformation matrices
ngl::Transformation m_trans_grid
ngl::Transformation m_trans_sphere
ngl::Transformation m_trans_cube
ngl::Transformation m_trans_level
ngl::Transformation m_trans_platform
ngl::Transformation m_position
ngl::Transformation m_transform
ngl::Transformation m_trans_coin
ngl::Transformation m_empty_trans
ngl::Vec3 m_textPos
position for debug text drawing
ngl::Vec3 m_textVel
velocity for debug text drawing
int m_w
width of the screen
int m_h
height of the screen
float m_lastTime
stores the last time the physics was updated
float m_rot
the rotation of the character
float m_prevRot
bool m_debug
enable or disable debug
int m_buttonCooldown
the number of ticks until the button is active again
bool m_bridgeDown
true if the bridge in level 4 is down
ngl::Vec3 m_initialBallPos
the starting position of the ball
float m_mass
the mass of the ball
bool m_attractEnable
enable stickiness
float m_gravityFactor
the value that is multiplied with -9.8 to produce the gravity value
std::string m_formOne
the name of the ball
std::string m_formTwo
the name of the legged character
ngl::Vec3 m_lightPosition
the position of the light camera used to create the shadow map
ngl::Camera m_lightCamera
camera from the lights point of view (used for shadows)
GLuint m_TextureID [2]
array to store multiple textures
GLuint m_subroutines [3]
array to store links to multiple shader subroutines
GLuint m_fboID
our FBO id used by the FBO
int m_time
our incrementing time variable to send to the shader for animation
float m_coinColour
coin colour
float m_lowThresholdKey
lower nois threshold
Detailed Description
This manages coin creation and collisions of the coins.
Definition at line 41 of file NGLDraw.h.
Constructor & Destructor Documentation
NGLDraw::NGLDraw ()
ctor this will have a valid OpenGL context so we can create gl stuff
Definition at line 21 of file NGLDraw.cpp.
References CollisionShape::addBox(), CollisionShape::addSphere(), BARRIER01, BOUNCE_PAD, BRIDGE_1, BRIDGE_2, CHAR_TYPE, COIN_REST, COIN_TYPE, ShaderFactory::createDebugShader(), createFramebufferObject(), ShaderFactory::createGroundShader(), ShaderFactory::createPhongShader(), ShaderFactory::createTextureShader(), Camera::getAngle(), Camera::getDistance(), increaseLowThreshold(), CollisionShape::instance(), m_animation, m_bridgeDown, m_buttonCooldown, m_cam, m_character, m_coinFactory, m_coinMesh, m_debug, m_finish, m_formOne, m_formTwo, m_gravityFactor, m_highScore, m_larryMesh, m_lastTime, m_level, m_level1Mesh, m_level2_1Mesh, m_level2_2Mesh, m_level2_3aMesh, m_level2_3bMesh, m_level3Mesh, m_level4_1Mesh, m_level4_2Mesh, m_level4Bridge1Mesh, m_level4Bridge2Mesh, m_level4RotPlatformMesh, m_level5Mesh, m_level5Stick, m_light, m_lightCamera, m_lightPosition, m_physics, m_platformFactory, m_platformMesh_barrier01, m_platformMesh_bouncePad, m_platformMesh_platform, m_prevRot, m_rotate, m_spinXFace, m_spinYFace, m_subroutines, m_text, m_textHighscore, m_TextureID, m_triggerFactory, makeNoise(), MOVE_PLATE, REST, ROTATING_L, Sky_BLUE, Sky_GREEN, and Sky_RED.
NGLDraw::~NGLDraw ()
dtor used to remove any NGL stuff created
Definition at line 530 of file NGLDraw.cpp.
References m_cam, and m_light.
Member Function Documentation
void NGLDraw::addCube ()
adds a cube used to test bullet physics
Definition at line 1355 of file NGLDraw.cpp.
References m_character, m_formOne, m_formTwo, and m_physics.
void NGLDraw::checkpoints ()
void NGLDraw::createFramebufferObject ()
create our fbo for shadows
Definition at line 1192 of file NGLDraw.cpp.
References m_fboID, m_TextureID, TEXTURE_HEIGHT, and TEXTURE_WIDTH.
void NGLDraw::debugPhysicsWorld (bool _value)
Definition at line 1336 of file NGLDraw.cpp.
References CollisionShape::instance(), m_debug, m_physics, and CollisionShape::printShapeMap().
void NGLDraw::draw ()
draw the scene
Definition at line 645 of file NGLDraw.cpp.
References BARRIER01, BOUNCE_PAD, BRIDGE_1, BRIDGE_2, drawDepth(), Camera::forcePos(), Camera::getEye(), Camera::getLook(), increaseCoinColour(), m_bodyTransform, m_bridgeDown, m_buttonCooldown, m_cam, m_character, m_coinFactory, m_coinMesh, m_debug, m_finish, m_formOne, m_formTwo, m_gravityFactor, m_h, m_highScore, m_larryMesh, m_level, m_level1Mesh, m_level2_1Mesh, m_level2_2Mesh, m_level2_3aMesh, m_level2_3bMesh, m_level3Mesh, m_level4_1Mesh, m_level4_2Mesh, m_level4Bridge1Mesh, m_level4Bridge2Mesh, m_level4RotPlatformMesh, m_level5Mesh, m_level5Stick, m_lightCamera, m_lightPosition, m_modelPos, m_mouseGlobalTX, m_physics, m_platformFactory, m_platformMesh_barrier01, m_platformMesh_bouncePad, m_platformMesh_platform, m_position, m_rot, m_spinXFace, m_spinYFace, m_text, m_textHighscore, m_textPos, m_TextureID, m_textVel, m_trans_coin, m_trans_grid, m_trans_level, m_trans_platform, m_trans_sphere, m_triggerFactory, m_w, MOVE_PLATE, MOVE_X, MOVE_Z, resetCoinColour(), resetLowThreshold(), ROTATING_L, Camera::setDistance(), shaderType(), Camera::snapPos(), and Camera::updatePos().
void NGLDraw::drawDepth ()
draw the scene from the lights POV for the depth pass
Definition at line 549 of file NGLDraw.cpp.
References Camera::getEye(), Camera::getLook(), m_bodyTransform, m_cam, m_character, m_fboID, m_formOne, m_formTwo, m_larryMesh, m_modelPos, m_mouseGlobalTX, m_physics, m_position, m_rot, m_spinXFace, m_spinYFace, m_trans_level, m_trans_sphere, shaderType(), TEXTURE_HEIGHT, TEXTURE_WIDTH, and Camera::updatePos().
Animation* NGLDraw::getAnimation () inline
returns a pointer to the animation manager
Definition at line 132 of file NGLDraw.h.
References m_animation.
Character* NGLDraw::getCharacter () inline
returns a pointer to the character
Definition at line 126 of file NGLDraw.h.
References m_character.
CoinFactory* NGLDraw::getCoinFactory () inline
returns a pointer to the coin factory
Definition at line 135 of file NGLDraw.h.
References m_coinFactory.
float NGLDraw::getGravityFactor ()
get the value that multiplies with -9.8 to create the gravity
Definition at line 1387 of file NGLDraw.cpp.
References m_gravityFactor.
Level* NGLDraw::getLevel () inline
returns a pointer to the level manager
Definition at line 129 of file NGLDraw.h.
References m_level.
PhysicsWorld* NGLDraw::getPhysicsWorld () inline
returns a pointer to the PhysicsWorld
Definition at line 123 of file NGLDraw.h.
References m_physics.
PlatformFactory* NGLDraw::getPlatformFactory () inline
returns a pointer to the platform factory
Definition at line 138 of file NGLDraw.h.
References m_platformFactory.
float NGLDraw::increaseCoinColour ()
reset the game values
Definition at line 306 of file NGLDraw.cpp.
References m_coinColour.
float NGLDraw::increaseLowThreshold ()
increment the lowThresholdKey for the disintegration effect
Definition at line 301 of file NGLDraw.cpp.
References m_lowThresholdKey.
int NGLDraw::increaseShaderTime ()
increments the variable m_time
Definition at line 1350 of file NGLDraw.cpp.
References m_time.
void NGLDraw::loadMatricesToShader (ngl::Transformation & _trans) private
method to load transform data to the shaders
void NGLDraw::makeNoise (float m_freq, float m_scale)
method to create a noise texture
Parameters
[in] m_freq the frequency of the noise pattern
[in] m_scale the scale (amplitude) of the noise pattern
Definition at line 320 of file NGLDraw.cpp.
References m_TextureID.
void NGLDraw::mouseMoveEvent (const SDL_MouseMotionEvent & _event)
this method is called every time a mouse is moved
Parameters
_event the SDL mouse event structure containing all mouse info
Definition at line 1228 of file NGLDraw.cpp.
References Camera::getAngle(), Camera::getHeight(), m_cam, m_origX, m_origY, m_rotate, Camera::setAngle(), and Camera::setHeight().
void NGLDraw::mousePressEvent (const SDL_MouseButtonEvent & _event)
this method is called every time a mouse button is presses
Parameters
_event the SDL mouse event structure containing all mouse info
Definition at line 1244 of file NGLDraw.cpp.
References m_origX, m_origY, and m_rotate.
void NGLDraw::mouseReleaseEvent (const SDL_MouseButtonEvent & _event)
this method is called everytime the mouse button is released
Parameters
_event the SDL mouse event structure containing all mouse info
Definition at line 1257 of file NGLDraw.cpp.
References m_rotate.
void NGLDraw::resetCoinColour ()
reset coin color to zero
Definition at line 315 of file NGLDraw.cpp.
References m_coinColour.
void NGLDraw::resetLowThreshold ()
reset the lowThresholdKey to zero
Definition at line 310 of file NGLDraw.cpp.
References m_lowThresholdKey.
void NGLDraw::resize (int _w, int _h)
resize our screen and set the camera aspect ratio
Parameters
[in] _w the new width
[in] _h the new height
Definition at line 538 of file NGLDraw.cpp.
References draw(), m_cam, m_h, m_text, m_w, and Camera::setShape().
void NGLDraw::restartGame ()
resets the character and game values
Definition at line 1392 of file NGLDraw.cpp.
References m_cam, and m_character.
void NGLDraw::restartGameValues ()
reset the game values
Definition at line 1397 of file NGLDraw.cpp.
References m_bridgeDown, m_coinFactory, m_highScore, m_physics, and m_platformFactory.
void NGLDraw::setGravityFactorNegative ()
decrements the gravity factor
Definition at line 1381 of file NGLDraw.cpp.
References m_gravityFactor, and m_physics.
void NGLDraw::setGravityFactorPositive ()
increments the gravity factor
Definition at line 1375 of file NGLDraw.cpp.
References m_gravityFactor, and m_physics.
void NGLDraw::shaderType (std::string _shaderName, ngl::Vec3 _shaderColour, bool stripe, float shine, ngl::Transformation & _trans)
method to pick a shader type and load object matrices to the shader
Parameters
[in] _shaderName the name of the shader
[in] _shaderColour the r,g,b colour values of the object
[in] stripe switch for turning on or off stripe patterns
[in] shine the specular reflectivity of the object
[in] _trans the object transform matrix
Definition at line 378 of file NGLDraw.cpp.
References Camera::getViewMatrix(), Camera::getVPMatrix(), increaseLowThreshold(), increaseShaderTime(), m_cam, m_lightCamera, m_mouseGlobalTX, m_subroutines, and m_transform.
void NGLDraw::updateDebugDraw ()
Definition at line 1297 of file NGLDraw.cpp.
References m_debug, m_empty_trans, m_physics, and shaderType().
void NGLDraw::updateDraw ()
Definition at line 1292 of file NGLDraw.cpp.
References draw().
void NGLDraw::updatePhysics (float time)
Definition at line 1305 of file NGLDraw.cpp.
References m_character, m_formOne, m_formTwo, m_gravityFactor, m_lastTime, m_physics, and m_triggerFactory.
void NGLDraw::updateRot ()
void NGLDraw::wheelEvent (const SDL_MouseWheelEvent & _event)
this method is called everytime the mouse wheel is moved
Parameters
_event the SDL mouse event structure containing all mouse info
Definition at line 1268 of file NGLDraw.cpp.
References Camera::getDistance(), m_cam, Camera::setDistance(), and ZOOM.
Member Data Documentation
std::unique_ptr<Animation> NGLDraw::m_animation private
class to handle all the animation
Definition at line 227 of file NGLDraw.h.
bool NGLDraw::m_attractEnable private
enable stickiness
Definition at line 361 of file NGLDraw.h.
ngl::Mat4 NGLDraw::m_bodyTransform private
transformation matrices
Definition at line 314 of file NGLDraw.h.
bool NGLDraw::m_bridgeDown private
true if the bridge in level 4 is down
Definition at line 352 of file NGLDraw.h.
int NGLDraw::m_buttonCooldown private
the number of ticks until the button is active again
Definition at line 349 of file NGLDraw.h.
Camera* NGLDraw::m_cam private
Our Camera.
Definition at line 201 of file NGLDraw.h.
std::unique_ptr<Character> NGLDraw::m_character private
class to manage the character
Definition at line 221 of file NGLDraw.h.
float NGLDraw::m_coinColour private
coin colour
Definition at line 398 of file NGLDraw.h.
std::unique_ptr<CoinFactory> NGLDraw::m_coinFactory private
class to manage the coins
Definition at line 230 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_coinMesh private
coin mesh
Definition at line 272 of file NGLDraw.h.
bool NGLDraw::m_debug private
enable or disable debug
Definition at line 346 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_empty_trans private
Definition at line 323 of file NGLDraw.h.
GLuint NGLDraw::m_fboID private
our FBO id used by the FBO
Definition at line 390 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_finish private
finish mesh
Definition at line 311 of file NGLDraw.h.
std::string NGLDraw::m_formOne private
the name of the ball
Definition at line 367 of file NGLDraw.h.
std::string NGLDraw::m_formTwo private
the name of the legged character
Definition at line 370 of file NGLDraw.h.
float NGLDraw::m_gravityFactor private
the value that is multiplied with -9.8 to produce the gravity value
Definition at line 364 of file NGLDraw.h.
int NGLDraw::m_h private
height of the screen
Definition at line 335 of file NGLDraw.h.
std::unique_ptr<HighScore> NGLDraw::m_highScore private
class to manage the high score
Definition at line 215 of file NGLDraw.h.
ngl::Vec3 NGLDraw::m_initialBallPos private
the starting position of the ball
Definition at line 355 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_larryMesh private
mesh for the character
Definition at line 242 of file NGLDraw.h.
float NGLDraw::m_lastTime private
stores the last time the physics was updated
Definition at line 338 of file NGLDraw.h.
std::unique_ptr<Level> NGLDraw::m_level private
class to manage all the level meshes
Definition at line 224 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level1_bouncePlatformMesh private
platform mesh
Definition at line 305 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level1Mesh private
level mesh
Definition at line 245 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level2_1Mesh private
level mesh
Definition at line 248 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level2_2Mesh private
level mesh
Definition at line 251 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level2_3aMesh private
level mesh
Definition at line 254 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level2_3bMesh private
level mesh
Definition at line 257 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level2Platform private
platform mesh
Definition at line 284 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level2Sliding1 private
platform mesh
Definition at line 287 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level2Sliding2 private
platform mesh
Definition at line 290 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level3Mesh private
level mesh
Definition at line 260 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level4_1Mesh private
level mesh
Definition at line 263 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level4_2Mesh private
level mesh
Definition at line 266 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level4Bridge1Mesh private
platform mesh
Definition at line 293 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level4Bridge2Mesh private
platform mesh
Definition at line 296 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level4RotPlatformMesh private
platform mesh
Definition at line 299 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level5Mesh private
level mesh
Definition at line 269 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level5MovingPlat private
platform mesh
Definition at line 302 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_level5Stick private
level 5 mesh
Definition at line 308 of file NGLDraw.h.
ngl::Light* NGLDraw::m_light private
a simple light use to illuminate the screen
Definition at line 209 of file NGLDraw.h.
ngl::Camera NGLDraw::m_lightCamera private
camera from the lights point of view (used for shadows)
Definition at line 378 of file NGLDraw.h.
ngl::Vec3 NGLDraw::m_lightPosition private
the position of the light camera used to create the shadow map
Definition at line 374 of file NGLDraw.h.
float NGLDraw::m_lowThresholdKey private
lower nois threshold
Definition at line 402 of file NGLDraw.h.
float NGLDraw::m_mass private
the mass of the ball
Definition at line 358 of file NGLDraw.h.
ngl::Vec3 NGLDraw::m_modelPos private
the model position for mouse movement
Definition at line 205 of file NGLDraw.h.
ngl::Mat4 NGLDraw::m_mouseGlobalTX private
used to store the global mouse transforms
Definition at line 197 of file NGLDraw.h.
float NGLDraw::m_origX private
the previous x mouse value
Definition at line 181 of file NGLDraw.h.
int NGLDraw::m_origXPos private
the previous x mouse value for Position changes
Definition at line 189 of file NGLDraw.h.
float NGLDraw::m_origY private
the previous y mouse value
Definition at line 185 of file NGLDraw.h.
int NGLDraw::m_origYPos private
the previous y mouse value for Position changes
Definition at line 193 of file NGLDraw.h.
std::unique_ptr<PhysicsWorld> NGLDraw::m_physics private
the PhysicsWorld from bullet physics
Definition at line 212 of file NGLDraw.h.
std::unique_ptr<PlatformFactory> NGLDraw::m_platformFactory private
class to manage all the platforms
Definition at line 233 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_platformMesh_barrier01 private
platform mesh
Definition at line 281 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_platformMesh_bouncePad private
platform mesh
Definition at line 278 of file NGLDraw.h.
std::unique_ptr<ngl::Obj> NGLDraw::m_platformMesh_platform private
platform mesh
Definition at line 275 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_position private
Definition at line 320 of file NGLDraw.h.
float NGLDraw::m_prevRot private
Definition at line 343 of file NGLDraw.h.
float NGLDraw::m_rot private
the rotation of the character
Definition at line 341 of file NGLDraw.h.
bool NGLDraw::m_rotate private
flag to indicate if the mouse button is pressed when dragging
Definition at line 177 of file NGLDraw.h.
int NGLDraw::m_spinXFace private
used to store the x rotation mouse value
Definition at line 169 of file NGLDraw.h.
int NGLDraw::m_spinYFace private
used to store the y rotation mouse value
Definition at line 173 of file NGLDraw.h.
GLuint NGLDraw::m_subroutines[3] private
array to store links to multiple shader subroutines
Definition at line 386 of file NGLDraw.h.
std::unique_ptr<Text> NGLDraw::m_text private
text object
Definition at line 236 of file NGLDraw.h.
std::unique_ptr<Text> NGLDraw::m_textHighscore private
text object
Definition at line 239 of file NGLDraw.h.
ngl::Vec3 NGLDraw::m_textPos private
position for debug text drawing
Definition at line 326 of file NGLDraw.h.
GLuint NGLDraw::m_TextureID[2] private
array to store multiple textures
Definition at line 382 of file NGLDraw.h.
ngl::Vec3 NGLDraw::m_textVel private
velocity for debug text drawing
Definition at line 329 of file NGLDraw.h.
int NGLDraw::m_time private
our incrementing time variable to send to the shader for animation
Definition at line 394 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_trans_coin private
Definition at line 322 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_trans_cube private
Definition at line 317 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_trans_grid private
Definition at line 315 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_trans_level private
Definition at line 318 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_trans_platform private
Definition at line 319 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_trans_sphere private
Definition at line 316 of file NGLDraw.h.
ngl::Transformation NGLDraw::m_transform private
Definition at line 321 of file NGLDraw.h.
std::unique_ptr<TriggerFactory> NGLDraw::m_triggerFactory private
class to manage the trigger volumes
Definition at line 218 of file NGLDraw.h.
int NGLDraw::m_w private
width of the screen
Definition at line 332 of file NGLDraw.h.
The documentation for this class was generated from the following files:
NGLDraw.h
NGLDraw.cpp