LARRY_GAME: Camera Class Reference
Camera Class Reference
Contains the camera used for rendering and controls its movement.
#include <Camera.h>
Public Member Functions
Camera (PhysicsWorld *_physics)
Constructor for the camera class.
~Camera ()
destructor
void updatePos (std::string _name)
Called each frame to update the camera's position.
void snapPos (std::string _name)
Can be called as an alternative to updatePos. Snaps the camera's position to the default position OR snaps the camera's position to the chosen angle.
void snapPos (std::string _name, float _angle)
void forcePos (std::string _name, float _angle)
Can be called as an alternative to updatePos. Sets the camera's ideal position based on input values and lets the PhysicsWorld handle the motion. Less jarring than snapPos.
void forcePos (std::string _name, float _angle, ngl::Vec3 _focus)
ngl::Vec4 getEye ()
Returns the Eye vector.
void setEye (ngl::Vec4 _eye)
Sets the Eye vector.
ngl::Vec4 getLook ()
Returns the Look vector.
void setLook (ngl::Vec4 _look)
Sets the Look vector.
ngl::Mat4 getViewMatrix ()
Returns the view matrix.
ngl::Mat4 getVPMatrix ()
Returns the ViewProjection matrix.
ngl::Mat4 getProjectionMatrix ()
Returns the Projection matrix.
float getDistance ()
Returns the distance between the camera and the focus.
void setDistance (float _distance)
Sets the distance between the camera and the focus.
float getHeight ()
returns the height of the camera
void setHeight (float _height)
sets the height of the camera
float getAngle ()
Returns the angle of the camera about the focus.
void setAngle (float _angle)
Sets the angle of the camera about the focus.
ngl::Vec3 getIdealPos ()
Returns the ideal position of the camera.
void setIdealPos (ngl::Vec3 _pos)
Sets the ideal position for the camera.
void setShape (int _angle, float _aspect, float _near, float _far)
Sets the camera's shape.
Private Attributes
ngl::Camera * m_camera
A pointer to an NGL::Camera.
ngl::Vec3 m_camIdealPos
The position that the camera will always accelerate towards.
float m_camDistance
The distance between the camera and the focus.
float m_tempDistance
Temporary distance for avoiding obstacles.
float m_camAngle
The angle of the camera about the focus.
float m_camHeight
The height of the camera relative to the focus.
ngl::Vec3 m_camVel
Velocity value used to amend with the physics simulation.
PhysicsWorld * m_physics
a pointer to the PhysicsWorld to use
Detailed Description
Contains the camera used for rendering and controls its movement.
Definition at line 12 of file Camera.h.
Constructor & Destructor Documentation
Camera::Camera (PhysicsWorld * _physics)
Constructor for the camera class.
Parameters
[in] _physics - pointer to the PhysicsWorld
Definition at line 5 of file Camera.cpp.
References m_camAngle, m_camDistance, m_camera, m_camHeight, m_physics, and m_tempDistance.
Camera::~Camera ()
destructor
Definition at line 26 of file Camera.cpp.
References m_camera.
Member Function Documentation
void Camera::forcePos (std::string _name, float _angle)
Can be called as an alternative to updatePos. Sets the camera's ideal position based on input values and lets the PhysicsWorld handle the motion. Less jarring than snapPos.
Parameters
[in] _name - the name of the PhysicsWorld body for the camera to focus on
[in] _angle - the angle to rotate the camera about the focus
[in] _focus - alternative focus for the camera if desired
Definition at line 154 of file Camera.cpp.
References PhysicsWorld::getLinVelocity(), PhysicsWorld::getPosition(), m_camAngle, m_camDistance, m_camera, m_camHeight, m_camIdealPos, m_camVel, m_physics, m_tempDistance, PhysicsWorld::rayTest(), and PhysicsWorld::setLinVelocity().
void Camera::forcePos (std::string _name, float _angle, ngl::Vec3 _focus)
Definition at line 217 of file Camera.cpp.
References PhysicsWorld::getLinVelocity(), PhysicsWorld::getPosition(), m_camAngle, m_camDistance, m_camera, m_camHeight, m_camIdealPos, m_camVel, m_physics, m_tempDistance, PhysicsWorld::rayTest(), and PhysicsWorld::setLinVelocity().
float Camera::getAngle ()
Returns the angle of the camera about the focus.
Definition at line 331 of file Camera.cpp.
References m_camAngle.
float Camera::getDistance ()
Returns the distance between the camera and the focus.
Definition at line 321 of file Camera.cpp.
References m_tempDistance.
ngl::Vec4 Camera::getEye ()
Returns the Eye vector.
Definition at line 286 of file Camera.cpp.
References m_camera.
float Camera::getHeight () inline
returns the height of the camera
Definition at line 86 of file Camera.h.
References m_camHeight.
ngl::Vec3 Camera::getIdealPos ()
Returns the ideal position of the camera.
Definition at line 341 of file Camera.cpp.
References m_camIdealPos.
ngl::Vec4 Camera::getLook ()
Returns the Look vector.
Definition at line 296 of file Camera.cpp.
References m_camera.
ngl::Mat4 Camera::getProjectionMatrix ()
Returns the Projection matrix.
Definition at line 316 of file Camera.cpp.
References m_camera.
ngl::Mat4 Camera::getViewMatrix ()
Returns the view matrix.
Definition at line 306 of file Camera.cpp.
References m_camera.
ngl::Mat4 Camera::getVPMatrix ()
Returns the ViewProjection matrix.
Definition at line 311 of file Camera.cpp.
References m_camera.
void Camera::setAngle (float _angle)
Sets the angle of the camera about the focus.
Parameters
[in] _angle - the angle to set in radians
Definition at line 336 of file Camera.cpp.
References m_camAngle.
void Camera::setDistance (float _distance)
Sets the distance between the camera and the focus.
Parameters
[in] _distance - the distance to set
Definition at line 326 of file Camera.cpp.
References m_tempDistance.
void Camera::setEye (ngl::Vec4 _eye)
Sets the Eye vector.
Parameters
[in] _eye - the vector to set
Definition at line 291 of file Camera.cpp.
References m_camera.
void Camera::setHeight (float _height) inline
sets the height of the camera
Parameters
[in] _height - the new height to set
Definition at line 91 of file Camera.h.
References m_camHeight.
void Camera::setIdealPos (ngl::Vec3 _pos)
Sets the ideal position for the camera.
Parameters
[in] _pos - the vector to set
Definition at line 346 of file Camera.cpp.
References m_camIdealPos.
void Camera::setLook (ngl::Vec4 _look)
Sets the Look vector.
Parameters
[in] _look - the vector to set
Definition at line 301 of file Camera.cpp.
References m_camera.
void Camera::setShape (int _angle, float _aspect, float _near, float _far)
Sets the camera's shape.
Parameters
[in] _angle - the View angle
[in] _aspect - the aspect ratio
[in] _near - near clipping distance
[in] _far - far clipping distance
Definition at line 351 of file Camera.cpp.
References m_camera.
void Camera::snapPos (std::string _name)
Can be called as an alternative to updatePos. Snaps the camera's position to the default position OR snaps the camera's position to the chosen angle.
Parameters
[in] _name - the name of the PhysicsWorld body for the camera to focus on
[in] _angle - the angle to rotate the camera about the focus
Definition at line 102 of file Camera.cpp.
References PhysicsWorld::addSphere(), PhysicsWorld::getLinVelocity(), PhysicsWorld::getPosition(), m_camAngle, m_camera, m_camHeight, m_camIdealPos, m_camVel, m_physics, m_tempDistance, PhysicsWorld::removeCollisionObj(), and PhysicsWorld::setGravityForBody().
void Camera::snapPos (std::string _name, float _angle)
Definition at line 128 of file Camera.cpp.
References PhysicsWorld::addSphere(), PhysicsWorld::getLinVelocity(), PhysicsWorld::getPosition(), m_camAngle, m_camera, m_camHeight, m_camIdealPos, m_camVel, m_physics, m_tempDistance, PhysicsWorld::removeCollisionObj(), and PhysicsWorld::setGravityForBody().
void Camera::updatePos (std::string _name)
Called each frame to update the camera's position.
Parameters
[in] _name - the name of the PhysicsWorld body for the camera to focus on
Definition at line 31 of file Camera.cpp.
References PhysicsWorld::getLinVelocity(), PhysicsWorld::getPosition(), m_camAngle, m_camDistance, m_camera, m_camHeight, m_camIdealPos, m_camVel, m_physics, m_tempDistance, PhysicsWorld::rayTest(), and PhysicsWorld::setLinVelocity().
Member Data Documentation
float Camera::m_camAngle private
The angle of the camera about the focus.
Definition at line 133 of file Camera.h.
float Camera::m_camDistance private
The distance between the camera and the focus.
Definition at line 127 of file Camera.h.
ngl::Camera* Camera::m_camera private
A pointer to an NGL::Camera.
Definition at line 121 of file Camera.h.
float Camera::m_camHeight private
The height of the camera relative to the focus.
Definition at line 136 of file Camera.h.
ngl::Vec3 Camera::m_camIdealPos private
The position that the camera will always accelerate towards.
Definition at line 124 of file Camera.h.
ngl::Vec3 Camera::m_camVel private
Velocity value used to amend with the physics simulation.
Definition at line 139 of file Camera.h.
PhysicsWorld* Camera::m_physics private
a pointer to the PhysicsWorld to use
Definition at line 142 of file Camera.h.
float Camera::m_tempDistance private
Temporary distance for avoiding obstacles.
Definition at line 130 of file Camera.h.
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp