LARRY_GAME: GUIDraw Class Reference
GUIDraw Class Reference
This class manages the intro GUI.
#include <GUIDraw.h>
Public Member Functions
GUIDraw ()
ctor
~GUIDraw ()
dtor used to remove textures
void loadAllTextures ()
loads the cutscene and menu images
void drawOpeningCredits ()
draws the opening credits screen
void drawOpeningCutscene (int cutsceneTime)
draws the opening cutscene
void drawOpeningTitleSequence (int cutsceneTime)
draws the opening title sequence
void drawTitleScreen ()
draws the title screen with 'PRESS ENTER' text
void drawTitleScreenNoText ()
draws the title screen without text
void drawMainMenu (int button)
draws the main menu
void drawControlsScreen ()
draws the controls screen
void drawExitScreen (int button)
draws the exit screen
void drawPauseScreen (int w, int h, bool resumeSelect, bool mainMenuSelect)
draws the pause screen
void drawTexture (float _b, float _t, float _l, float _r, float _d)
draws a texture on a two triangle quad
void loadTexture (std::string filePath, int ID)
loads the texture from a file
void drawQuadColour (float _b, float _t, float _l, float _r, ngl::Vec3 colour, float alpha)
draws a colour on a two triangle quad
void drawMenuOpenTop (float move)
draws the top part of the menu texture
void drawMenuOpenBottom (float move)
draws the bottom part of the menu texture
Private Attributes
std::unique_ptr< Text > m_textPause
the text object for the 'PAUSE' title
std::unique_ptr< Text > m_textPauseOptions
the text object for the pause options - 'RESUME' and 'MAIN MENU'
GLuint m_textureMenuID [401]
an array of textures used for the menus and cutscene
Detailed Description
This class manages the intro GUI.
Definition at line 12 of file GUIDraw.h.
Constructor & Destructor Documentation
GUIDraw::GUIDraw ()
ctor
Definition at line 10 of file GUIDraw.cpp.
References m_textPause, and m_textPauseOptions.
GUIDraw::~GUIDraw ()
dtor used to remove textures
Definition at line 43 of file GUIDraw.cpp.
References m_textureMenuID.
Member Function Documentation
void GUIDraw::drawControlsScreen ()
draws the controls screen
Definition at line 158 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawExitScreen (int button)
draws the exit screen
Parameters
[in] button the id of the button the mouse is over
Definition at line 165 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawMainMenu (int button)
draws the main menu
Parameters
[in] button the id of the button the mouse is over
Definition at line 131 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawMenuOpenBottom (float move)
draws the bottom part of the menu texture
Parameters
[in] move the distance the texture will move downwards
Definition at line 212 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawMenuOpenTop (float move)
draws the top part of the menu texture
Parameters
[in] move the distance the texture will move upwards
Definition at line 205 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawOpeningCredits ()
draws the opening credits screen
Definition at line 96 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawOpeningCutscene (int cutsceneTime)
draws the opening cutscene
Parameters
[in] cutsceneTime the frame number of the cutscene to draw
Definition at line 103 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawOpeningTitleSequence (int cutsceneTime)
draws the opening title sequence
Parameters
[in] cutsceneTime the frame number of the sequence to draw
Definition at line 110 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawPauseScreen (int w, int h, bool resumeSelect, bool mainMenuSelect)
draws the pause screen
Parameters
[in] w the width of the screen
[in] h the height of the screen
[in] resumeSelect flag to indicate if mouse is over 'resume' text
[in] mainMenuSelect flag to indicate if mouse is over 'mainMenu' text
Definition at line 186 of file GUIDraw.cpp.
References m_textPause, and m_textPauseOptions.
void GUIDraw::drawQuadColour (float _b, float _t, float _l, float _r, ngl::Vec3 colour, float alpha)
draws a colour on a two triangle quad
Parameters
[in] _b the bottom of the quad
[in] _t the top of the quad
[in] _b the left side of the quad
[in] _b the right side of the quad
[in] colour the colour of the quad
[in] alpha the transparency of the quad
Definition at line 296 of file GUIDraw.cpp.
void GUIDraw::drawTexture (float _b, float _t, float _l, float _r, float _d)
draws a texture on a two triangle quad
Parameters
[in] _b the bottom of the quad
[in] _t the top of the quad
[in] _b the left side of the quad
[in] _b the right side of the quad
[in] _d the distance of the quad to the camera used for layering textures
Definition at line 219 of file GUIDraw.cpp.
void GUIDraw::drawTitleScreen ()
draws the title screen with 'PRESS ENTER' text
Definition at line 124 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::drawTitleScreenNoText ()
draws the title screen without text
Definition at line 117 of file GUIDraw.cpp.
References drawTexture(), and m_textureMenuID.
void GUIDraw::loadAllTextures ()
loads the cutscene and menu images
Definition at line 50 of file GUIDraw.cpp.
References loadTexture().
void GUIDraw::loadTexture (std::string filePath, int ID)
loads the texture from a file
Parameters
[in] filePath path to the texture file
[in] ID the id of the texture to bind
Definition at line 271 of file GUIDraw.cpp.
References m_textureMenuID.
Member Data Documentation
std::unique_ptr<Text> GUIDraw::m_textPause private
the text object for the 'PAUSE' title
Definition at line 91 of file GUIDraw.h.
std::unique_ptr<Text> GUIDraw::m_textPauseOptions private
the text object for the pause options - 'RESUME' and 'MAIN MENU'
Definition at line 94 of file GUIDraw.h.
GLuint GUIDraw::m_textureMenuID[401] private
an array of textures used for the menus and cutscene
Definition at line 97 of file GUIDraw.h.
The documentation for this class was generated from the following files:
GUIDraw.h
GUIDraw.cpp