LARRY_GAME: Level Class Reference
Level Class Reference
This class manages the levels.
#include <Level.h>
Public Member Functions
Level (PhysicsWorld *_physics)
ctor of the animation class
void createLevel (std::string _levelName, ngl::Vec3 _pos)
used to create a level mesh
void checkpoints (bool _shapeshift)
it checks the position of the checkpoints and if the character goes through them saves a new initial position
ngl::Vec3 getInitialPos ()
returns the initial position
Private Attributes
PhysicsWorld * m_physics
pointer to physics world
ngl::Vec3 m_initialBallPos
initial position of the character
std::unique_ptr< Text > m_text
pointer to text
ngl::Vec3 m_charPos
current position of character
std::string m_formOne
name of one form of character
std::string m_formTwo
name of one form of character
bool m_check1
if character has gone through checkpoint 1
bool m_check2
if character has gone through checkpoint 2
bool m_check3
if character has gone through checkpoint 3
bool m_check4
if character has gone through checkpoint 4
bool m_check5
if character has gone through checkpoint 5
Detailed Description
This class manages the levels.
Definition at line 18 of file Level.h.
Constructor & Destructor Documentation
Level::Level (PhysicsWorld * _physics)
ctor of the animation class
Definition at line 3 of file Level.cpp.
References CollisionShape::addLevelMesh(), CollisionShape::instance(), m_check1, m_check2, m_check3, m_check4, m_check5, m_formOne, m_formTwo, m_initialBallPos, m_physics, and m_text.
Member Function Documentation
void Level::checkpoints (bool _shapeshift)
it checks the position of the checkpoints and if the character goes through them saves a new initial position
Parameters
_shapeshift says which character you currently are
Definition at line 45 of file Level.cpp.
References PhysicsWorld::getPosition(), m_charPos, m_check1, m_check2, m_check3, m_check4, m_check5, m_formOne, m_formTwo, m_initialBallPos, m_physics, and m_text.
void Level::createLevel (std::string _levelName, ngl::Vec3 _pos)
used to create a level mesh
Parameters
_levelName the name that has been given to the level mesh
_pos the position that the level should be
Definition at line 35 of file Level.cpp.
References PhysicsWorld::addLevelMesh(), and m_physics.
ngl::Vec3 Level::getInitialPos ()
returns the initial position
Definition at line 40 of file Level.cpp.
References m_initialBallPos.
Member Data Documentation
ngl::Vec3 Level::m_charPos private
current position of character
Definition at line 56 of file Level.h.
bool Level::m_check1 private
if character has gone through checkpoint 1
Definition at line 68 of file Level.h.
bool Level::m_check2 private
if character has gone through checkpoint 2
Definition at line 72 of file Level.h.
bool Level::m_check3 private
if character has gone through checkpoint 3
Definition at line 76 of file Level.h.
bool Level::m_check4 private
if character has gone through checkpoint 4
Definition at line 80 of file Level.h.
bool Level::m_check5 private
if character has gone through checkpoint 5
Definition at line 84 of file Level.h.
std::string Level::m_formOne private
name of one form of character
Definition at line 60 of file Level.h.
std::string Level::m_formTwo private
name of one form of character
Definition at line 64 of file Level.h.
ngl::Vec3 Level::m_initialBallPos private
initial position of the character
Definition at line 48 of file Level.h.
PhysicsWorld* Level::m_physics private
pointer to physics world
Definition at line 44 of file Level.h.
std::unique_ptr<Text> Level::m_text private
pointer to text
Definition at line 52 of file Level.h.
The documentation for this class was generated from the following files:
Level.h
Level.cpp