LARRY_GAME: Platform Class Reference
Platform Class Reference
A selection of platforms that act as moving parts of the level.
#include <Platform.h>
Public Member Functions
Platform (ngl::Vec3 _pos, std::string _platName, PlatType _platType, PhysicsWorld *_physics)
Constructor.
void createPlatform ()
Creates a platform in the PhysicsWorld.
void movePlatform (float _vel, float _range, Direction _d)
Moves the platform in a back-and-forth motion.
void addRot (int _deg)
Add rotation to the platform.
void setRot (int _rot)
Set rotation of the platform.
void rotatePlatform (std::string _axis)
Called each frame to update the platform's rotation.
ngl::Vec3 getPlatformPos ()
Returns the position of the platform.
std::string getPlatformName ()
Returns the platform's name.
PlatType getPlatType ()
Returns the platform's type.
Private Attributes
PhysicsWorld * m_physics
a pointer to the PhysicsWorld
int m_platformDirection
the Direction of motion, either 1 or -1
ngl::Vec3 m_pos
the central position of the platform
std::string m_platName
the name used as the platform's ID
PlatType m_platType
the type of platform
int m_deg
the angle left to rotate through
int m_rot
the cumulative angle of the platform
Detailed Description
A selection of platforms that act as moving parts of the level.
Definition at line 37 of file Platform.h.
Constructor & Destructor Documentation
Platform::Platform (ngl::Vec3 _pos, std::string _platName, PlatType _platType, PhysicsWorld * _physics)
Constructor.
Parameters
[in] _pos - The central position for the platform
[in] _platName - A name to use as ID for this platform
[in] _platType - the type of platform to use
[in] _physics - pointer to the PhysicsWorld
Definition at line 4 of file Platform.cpp.
References CollisionShape::addMesh(), BARRIER01, BARRIER_LARGE, BOUNCE_PAD, BRIDGE_1, BRIDGE_2, CollisionShape::instance(), m_deg, m_physics, m_platformDirection, m_platName, m_platType, m_pos, m_rot, MOVE_PLATE, and ROTATING_L.
Member Function Documentation
void Platform::addRot (int _deg)
Add rotation to the platform.
Parameters
[in] m_deg - the angle to rotate in degrees
Definition at line 69 of file Platform.cpp.
References m_deg.
void Platform::createPlatform ()
Creates a platform in the PhysicsWorld.
Definition at line 62 of file Platform.cpp.
References PhysicsWorld::addPlatform(), m_physics, m_platName, and m_pos.
std::string Platform::getPlatformName ()
Returns the platform's name.
Definition at line 188 of file Platform.cpp.
References m_platName.
ngl::Vec3 Platform::getPlatformPos ()
Returns the position of the platform.
Definition at line 183 of file Platform.cpp.
References PhysicsWorld::getPosition(), m_physics, and m_platName.
PlatType Platform::getPlatType ()
Returns the platform's type.
Definition at line 193 of file Platform.cpp.
References m_platType.
void Platform::movePlatform (float _vel, float _range, Direction _d)
Moves the platform in a back-and-forth motion.
Parameters
[in] _vel - the speed of the motion
[in] _range - the distance either side of the original position that the platform can go
[in] _d - the axis on which the platform may move
Definition at line 117 of file Platform.cpp.
References PhysicsWorld::getPosition(), m_physics, m_platformDirection, m_platName, m_pos, MOVE_X, MOVE_Y, MOVE_Z, and PhysicsWorld::setLinVelocity().
void Platform::rotatePlatform (std::string _axis)
Called each frame to update the platform's rotation.
Parameters
_axis - the axis around which to rotate
Definition at line 80 of file Platform.cpp.
References PhysicsWorld::getTransformMatrix(), m_deg, m_physics, m_platName, m_rot, and PhysicsWorld::setTransformMatrix().
void Platform::setRot (int _rot)
Set rotation of the platform.
Parameters
[in] _rot - the angle to rotate in degrees
Definition at line 75 of file Platform.cpp.
References m_rot.
Member Data Documentation
int Platform::m_deg private
the angle left to rotate through
Definition at line 106 of file Platform.h.
PhysicsWorld* Platform::m_physics private
a pointer to the PhysicsWorld
Definition at line 91 of file Platform.h.
int Platform::m_platformDirection private
the Direction of motion, either 1 or -1
Definition at line 94 of file Platform.h.
std::string Platform::m_platName private
the name used as the platform's ID
Definition at line 100 of file Platform.h.
PlatType Platform::m_platType private
the type of platform
Definition at line 103 of file Platform.h.
ngl::Vec3 Platform::m_pos private
the central position of the platform
Definition at line 97 of file Platform.h.
int Platform::m_rot private
the cumulative angle of the platform
Definition at line 109 of file Platform.h.
The documentation for this class was generated from the following files:
Platform.h
Platform.cpp