LARRY_GAME: Coin Class Reference
Coin Class Reference
This class creates the coin.
#include <Coin.h>
Public Member Functions
Coin (ngl::Vec3 _pos, std::string _id, PhysicsWorld *_physics)
ctor of the animation class
~Coin ()
dtor of the animation class
ngl::Vec3 getCoinPos ()
returns a vector position of the coin
Trigger * getTrigger ()
returns a pointer to the coin's trigger
bool isCoinHit (std::string _playerName)
returns bool value whether player is in contact with coin's trigger
void setCoinState (bool _state)
set whether coin state is active or deactivated
void startTime ()
start the coin timer
bool getCoinState ()
returns the current state of coin
float getTime ()
returns the current coin time
Private Attributes
Trigger * m_coinTrigger
pointer to the trigger class, used for the coin's trigger box
PhysicsWorld * m_physics
pointer to our physicsWorld
ngl::Vec3 m_coinPos
vector position of the coin (x,y,z)
std::string m_coinID
identifier for coin
ngl::Vec3 m_bboxMin
min bounding box co-ordinates for coin's trigger (xmin,ymin,zmin)
ngl::Vec3 m_bboxMax
max bounding box co-ordinates for coin's trigger (xmax,ymax,zmax)
bool m_coinState =1
holds the current state of the coin
LTimer m_coinTimer
store the current age of the coin
Detailed Description
This class creates the coin.
Definition at line 16 of file Coin.h.
Constructor & Destructor Documentation
Coin::Coin (ngl::Vec3 _pos, std::string _id, PhysicsWorld * _physics)
ctor of the animation class
Parameters
_pos vector position of coin (x,y,z)
_id identifier for coin
_physics pointer to our PhysicsWorld
Definition at line 3 of file Coin.cpp.
References m_bboxMax, m_bboxMin, m_coinID, m_coinPos, m_coinTimer, m_coinTrigger, m_physics, LTimer::pause(), and LTimer::start().
Coin::~Coin ()
dtor of the animation class
Definition at line 20 of file Coin.cpp.
References m_coinTrigger.
Member Function Documentation
ngl::Vec3 Coin::getCoinPos ()
returns a vector position of the coin
Definition at line 26 of file Coin.cpp.
References m_coinPos.
bool Coin::getCoinState () inline
returns the current state of coin
Definition at line 55 of file Coin.h.
References m_coinState.
float Coin::getTime () inline
returns the current coin time
Definition at line 60 of file Coin.h.
References LTimer::getTicks(), and m_coinTimer.
Trigger * Coin::getTrigger ()
returns a pointer to the coin's trigger
Definition at line 31 of file Coin.cpp.
References m_coinTrigger.
bool Coin::isCoinHit (std::string _playerName)
returns bool value whether player is in contact with coin's trigger
Definition at line 36 of file Coin.cpp.
References Trigger::isHit(), and m_coinTrigger.
void Coin::setCoinState (bool _state)
set whether coin state is active or deactivated
Definition at line 42 of file Coin.cpp.
References m_coinState.
void Coin::startTime ()
start the coin timer
Definition at line 54 of file Coin.cpp.
References m_coinTimer, and LTimer::unpause().
Member Data Documentation
ngl::Vec3 Coin::m_bboxMax private
max bounding box co-ordinates for coin's trigger (xmax,ymax,zmax)
Definition at line 87 of file Coin.h.
ngl::Vec3 Coin::m_bboxMin private
min bounding box co-ordinates for coin's trigger (xmin,ymin,zmin)
Definition at line 83 of file Coin.h.
std::string Coin::m_coinID private
identifier for coin
Definition at line 79 of file Coin.h.
ngl::Vec3 Coin::m_coinPos private
vector position of the coin (x,y,z)
Definition at line 75 of file Coin.h.
bool Coin::m_coinState =1 private
holds the current state of the coin
Definition at line 91 of file Coin.h.
LTimer Coin::m_coinTimer private
store the current age of the coin
Definition at line 95 of file Coin.h.
Trigger* Coin::m_coinTrigger private
pointer to the trigger class, used for the coin's trigger box
Definition at line 67 of file Coin.h.
PhysicsWorld* Coin::m_physics private
pointer to our physicsWorld
Definition at line 71 of file Coin.h.
The documentation for this class was generated from the following files:
Coin.h
Coin.cpp