LARRY_GAME: HighScore Class Reference
HighScore Class Reference
This class writes out and reads the highscore for the game.
#include <HighScore.h>
Public Member Functions
HighScore ()
ctor for HighScore class
void highScoreStart ()
starts the highscore timer
void highScorePause ()
method pauses the highscore
void highScoreRead ()
reads the value from a txt file
void setCurrentScore ()
sets the current score
void highScoreWrite ()
writes the highscore to a txt file
void setHighScore ()
sets the highscore
int getHighScore ()
returns the highscore
int getCurrentScore ()
returns the current score
int getScoreTime ()
returns the current score timer
Private Attributes
int m_currentScore
current score value
int m_highScore
highscore value
QString m_highScoreString
string value for the read file
LTimer m_scoreTimer
timer for the score
Detailed Description
This class writes out and reads the highscore for the game.
Definition at line 13 of file HighScore.h.
Constructor & Destructor Documentation
HighScore::HighScore ()
ctor for HighScore class
Definition at line 7 of file HighScore.cpp.
References m_currentScore, m_highScore, and m_highScoreString.
Member Function Documentation
int HighScore::getCurrentScore () inline
returns the current score
Definition at line 51 of file HighScore.h.
References m_currentScore.
int HighScore::getHighScore () inline
returns the highscore
Definition at line 47 of file HighScore.h.
References m_highScore.
int HighScore::getScoreTime () inline
returns the current score timer
Definition at line 55 of file HighScore.h.
References LTimer::getTicks(), and m_scoreTimer.
void HighScore::highScorePause ()
method pauses the highscore
Definition at line 19 of file HighScore.cpp.
References m_scoreTimer, and LTimer::pause().
void HighScore::highScoreRead ()
reads the value from a txt file
Definition at line 40 of file HighScore.cpp.
References exit(), m_highScore, and m_highScoreString.
void HighScore::highScoreStart ()
starts the highscore timer
Definition at line 14 of file HighScore.cpp.
References m_scoreTimer, and LTimer::start().
void HighScore::highScoreWrite ()
writes the highscore to a txt file
Definition at line 56 of file HighScore.cpp.
References m_highScore.
void HighScore::setCurrentScore ()
sets the current score
Definition at line 24 of file HighScore.cpp.
References LTimer::getTicks(), m_currentScore, and m_scoreTimer.
void HighScore::setHighScore ()
sets the highscore
Definition at line 29 of file HighScore.cpp.
References highScoreWrite(), m_currentScore, m_highScore, and setCurrentScore().
Member Data Documentation
int HighScore::m_currentScore private
current score value
Definition at line 60 of file HighScore.h.
int HighScore::m_highScore private
highscore value
Definition at line 64 of file HighScore.h.
QString HighScore::m_highScoreString private
string value for the read file
Definition at line 68 of file HighScore.h.
LTimer HighScore::m_scoreTimer private
timer for the score
Definition at line 72 of file HighScore.h.
The documentation for this class was generated from the following files:
HighScore.h
HighScore.cpp