LARRY_GAME: Character Class Reference
Character Class Reference
This class manages/creates is for all the character abilities and attributes.
#include <Character.h>
Public Member Functions
Character (PhysicsWorld *_physics)
ctor for HighScore class
~Character ()
destructor for HighScore class
void shapeshift ()
method to change the character from ball to leged and back
void createCharacter (ngl::Vec3 _pos)
creates the character at the given position
void jumpImpulse ()
creates a jump impulse
void stopJumpHopTimer ()
stop the timer for the hop
void startJumpHopTimer ()
starts the timer for the hop
bool detectCollisionForJump ()
detects if character is standing on a mesh
void setCameraInfo (ngl::Vec4 &_camVector)
sets camera viewing direction vector
void characterMove (ngl::Vec3 _move)
makes character move based on the direction vector
void clampVel (std::string _shape)
clamps velocity based on name
void speed (std::string _shape)
increases the character velocity
ngl::Vec3 getMove ()
returns the direction vector of the character
float getMass ()
returns the current mass of the character
float getMaxVelocity ()
returns the max velocity
float getMultiplier ()
returns the velocity multiplier of the character
int getDoubleJump ()
returns if the character is doing the double jump
float getJumpHopTime ()
returns the jump hop time
bool getPhase ()
returns the current phase of the object (ball or legged form)
ngl::Vec3 getPlatformVelocity ()
gets the velocity of the platform
void setShiftable (bool _canShift)
enable/disable the characters ability to shapeshift
void godMode ()
turn on cheats (disable gravity for character one in order to debug the levels)
void setMassPositive ()
increment the mass of the character
void setMassNegative ()
decrements the mass of the character
void setMaxVelPositive ()
increments the max velocity of the character
void setMaxVelNegative ()
decrements the max velocity of the character
void setMultiplierPositive ()
increments the multiplier of the velocity of the character
void setMultiplierNegative ()
decrements the multiplier of the velocity of the character
void freezeCharacter ()
freezes the character at his current position
ngl::Vec3 getGravityDir ()
returns the direction of the gravity of an object
ngl::Vec3 getCollisionNormal (ngl::Vec3 a, ngl::Vec3 b)
returns the normal of the collision object that the ray collides with
void attractForce (float _gravityFactor, float _attractForceStr, std::string _name)
returns the normal of the collision object that the ray collides with
void setJumpForcePositive ()
increments the jump force
void setJumpForceNegative ()
decrements the jump force
void setJumpHopMaxTimePositive ()
increments the time that the jump force is applied to the character
void setJumpHopMaxTimeNegative ()
decrements the time that the jump force is applied to the character
float getJumpForce ()
returns the jump force value
int getJumpHopMaxTime ()
returns the jump hop time
void setFrictionPositive ()
increment the friction character
void setFrictionNegative ()
decrement the friction of the character
float getFriction ()
returns the friction value of the character
void setGravityForCharacter (std::string _shape, ngl::Vec3 _vec)
sets the gravity for the character
void resetCharacter (Camera *_cam, ngl::Vec3 _charPos)
sets the gravity for the character
void setAttractFlag (bool _value)
turn on or off the stickiness (attraction force)
bool getClampFlag ()
return the current clamp mode
void setClampFlag (bool _value)
sets the clamping on or off
Private Attributes
bool m_shiftable
controls if character can shapeshift or not
float m_mulitplier
the velocity multiplier
float m_mass
the mass of the character
float m_maxVelocity
the maximum velocity variable
ngl::Vec4 m_cameraDir
camera direction vector
PhysicsWorld * m_physics
holds the pointer to the physics world
ngl::Vec3 m_collisionNormal
the normal of the collision check
ngl::Vec3 m_charPos
character position
ngl::Vec3 m_move
the movement direction vector of the character
bool m_attractEnable
enables or disables the stickiness (attraction force)
LTimer m_freezeTimer
the length of the freeze for the character
std::string m_formOne
character in form one name
std::string m_formTwo
character in form two name
LTimer jumpHopTimer
timer for the amount of time that the space bar is pressed during the characters jump
float m_jumpForce
the jumping impulse force
int m_jumpHopMaxTime
the maximum time that the jump force can be applied during a single jump
float m_friction
the friction of the character
bool m_doubleJump
the state of the character's double jump
float m_jumpHopTime
the time that the character is jumping for
ngl::Vec3 m_oldPlatformVelocity
the velocity of the platform from the previous frame
ngl::Vec3 m_platformVelocity
the velocity of the current frame of the platform
ngl::Vec3 m_initialBallPos
initial position of the ball character
bool m_clamp
disable or enable the velocity clamp
bool m_shapeshift
character phase (form)
Detailed Description
This class manages/creates is for all the character abilities and attributes.
Definition at line 19 of file Character.h.
Constructor & Destructor Documentation
Character::Character (PhysicsWorld * _physics)
ctor for HighScore class
Definition at line 7 of file Character.cpp.
References CollisionShape::addCapsule(), CollisionShape::addSphere(), CollisionShape::instance(), jumpHopTimer, m_attractEnable, m_clamp, m_doubleJump, m_formOne, m_formTwo, m_friction, m_initialBallPos, m_jumpForce, m_jumpHopMaxTime, m_mass, m_maxVelocity, m_mulitplier, m_oldPlatformVelocity, m_physics, m_platformVelocity, m_shapeshift, m_shiftable, and LTimer::start().
Character::~Character ()
destructor for HighScore class
Definition at line 38 of file Character.cpp.
Member Function Documentation
void Character::attractForce (float _gravityFactor, float _attractForceStr, std::string _name)
returns the normal of the collision object that the ray collides with
Parameters
[in] _gravityFactor the multiplier of the gravity
[in] _attractForceStr the strength of the force that pulls towards the object
[in] _name the name of the shape of the character to make sticky
Definition at line 303 of file Character.cpp.
References getCollisionNormal(), PhysicsWorld::getPosition(), m_attractEnable, m_collisionNormal, m_physics, and PhysicsWorld::setGravityForBody().
void Character::characterMove (ngl::Vec3 _move)
makes character move based on the direction vector
Parameters
[in] _move character move direction vector
Definition at line 119 of file Character.cpp.
References PhysicsWorld::applyForceCentral(), clampVel(), detectCollisionForJump(), PhysicsWorld::getLinVelocity(), PhysicsWorld::getPosition(), LTimer::getTicks(), PhysicsWorld::getVelocityOfPlatform(), jumpHopTimer, jumpImpulse(), m_cameraDir, m_clamp, m_collisionNormal, m_doubleJump, m_formOne, m_formTwo, m_friction, m_jumpHopMaxTime, m_jumpHopTime, m_maxVelocity, m_mulitplier, m_oldPlatformVelocity, m_physics, m_platformVelocity, m_shapeshift, PhysicsWorld::setLinVelocity(), and LTimer::stop().
void Character::clampVel (std::string _shape)
clamps velocity based on name
Parameters
[in] _shape name of the object to clamp velocity
Definition at line 257 of file Character.cpp.
References PhysicsWorld::getLinVelocity(), m_maxVelocity, m_physics, PhysicsWorld::setLinVelocity(), and speed().
void Character::createCharacter (ngl::Vec3 _pos)
creates the character at the given position
Parameters
[in] _pos the starting position for the character
Definition at line 40 of file Character.cpp.
References PhysicsWorld::addSphere(), m_formOne, m_initialBallPos, m_mass, and m_physics.
bool Character::detectCollisionForJump ()
detects if character is standing on a mesh
Definition at line 99 of file Character.cpp.
References PhysicsWorld::getPosition(), m_formOne, m_formTwo, m_physics, m_shapeshift, and PhysicsWorld::rayTest().
void Character::freezeCharacter ()
freezes the character at his current position
Definition at line 286 of file Character.cpp.
References PhysicsWorld::freezeBody(), LTimer::getTicks(), m_formOne, m_freezeTimer, m_physics, LTimer::reset(), LTimer::start(), and LTimer::stop().
bool Character::getClampFlag () inline
return the current clamp mode
Definition at line 216 of file Character.h.
References m_clamp.
ngl::Vec3 Character::getCollisionNormal (ngl::Vec3 a, ngl::Vec3 b)
returns the normal of the collision object that the ray collides with
Parameters
[in] a the first point of the ray
[in] b the second point of the ray
Definition at line 362 of file Character.cpp.
References m_physics, and PhysicsWorld::rayNormalTest().
int Character::getDoubleJump () inline
returns if the character is doing the double jump
Definition at line 94 of file Character.h.
References m_doubleJump.
float Character::getFriction () inline
returns the friction value of the character
Definition at line 195 of file Character.h.
References m_friction.
ngl::Vec3 Character::getGravityDir ()
returns the direction of the gravity of an object
Definition at line 347 of file Character.cpp.
References m_collisionNormal.
float Character::getJumpForce () inline
returns the jump force value
Definition at line 179 of file Character.h.
References m_jumpForce.
int Character::getJumpHopMaxTime () inline
returns the jump hop time
Definition at line 183 of file Character.h.
References m_jumpHopMaxTime.
float Character::getJumpHopTime () inline
returns the jump hop time
Definition at line 98 of file Character.h.
References m_jumpHopTime.
float Character::getMass () inline
returns the current mass of the character
Definition at line 82 of file Character.h.
References m_mass.
float Character::getMaxVelocity () inline
returns the max velocity
Definition at line 86 of file Character.h.
References m_maxVelocity.
ngl::Vec3 Character::getMove () inline
returns the direction vector of the character
Definition at line 78 of file Character.h.
References m_move.
float Character::getMultiplier () inline
returns the velocity multiplier of the character
Definition at line 90 of file Character.h.
References m_mulitplier.
bool Character::getPhase () inline
returns the current phase of the object (ball or legged form)
Definition at line 102 of file Character.h.
References m_shapeshift.
ngl::Vec3 Character::getPlatformVelocity () inline
gets the velocity of the platform
Definition at line 106 of file Character.h.
References m_platformVelocity.
void Character::godMode ()
turn on cheats (disable gravity for character one in order to debug the levels)
Definition at line 374 of file Character.cpp.
References m_formOne, m_physics, and PhysicsWorld::setGravityForBody().
void Character::jumpImpulse ()
creates a jump impulse
Definition at line 83 of file Character.cpp.
References PhysicsWorld::addImpulse(), detectCollisionForJump(), PhysicsWorld::getLinVelocity(), LTimer::getTicks(), jumpHopTimer, m_formTwo, m_jumpForce, m_physics, m_shapeshift, and PhysicsWorld::setLinVelocity().
void Character::resetCharacter (Camera * _cam, ngl::Vec3 _charPos)
sets the gravity for the character
Parameters
[in] _cam the object to set the gravity to
[in] _charPos the position of the character
Definition at line 444 of file Character.cpp.
References PhysicsWorld::addSphere(), m_clamp, m_formOne, m_formTwo, m_initialBallPos, m_mass, m_physics, m_shapeshift, PhysicsWorld::removeCollisionObj(), and Camera::snapPos().
void Character::setAttractFlag (bool _value)
turn on or off the stickiness (attraction force)
Parameters
[in] _value enable or disable attarction
Definition at line 464 of file Character.cpp.
References m_attractEnable.
void Character::setCameraInfo (ngl::Vec4 & _camVector)
sets camera viewing direction vector
Parameters
[in] _camVector set the camera direction vector
Definition at line 368 of file Character.cpp.
References m_cameraDir.
void Character::setClampFlag (bool _value)
sets the clamping on or off
Parameters
[in] _value set the clamping value
Definition at line 469 of file Character.cpp.
References m_clamp.
void Character::setFrictionNegative ()
decrement the friction of the character
Definition at line 434 of file Character.cpp.
References m_friction.
void Character::setFrictionPositive ()
increment the friction character
Definition at line 429 of file Character.cpp.
References m_friction.
void Character::setGravityForCharacter (std::string _shape, ngl::Vec3 _vec)
sets the gravity for the character
Parameters
[in] _shape the object to set the gravity to
[in] _vec the direction of the gravity
Definition at line 439 of file Character.cpp.
References m_physics, and PhysicsWorld::setGravityForBody().
void Character::setJumpForceNegative ()
decrements the jump force
Definition at line 415 of file Character.cpp.
References m_jumpForce.
void Character::setJumpForcePositive ()
increments the jump force
Definition at line 410 of file Character.cpp.
References m_jumpForce.
void Character::setJumpHopMaxTimeNegative ()
decrements the time that the jump force is applied to the character
Definition at line 424 of file Character.cpp.
References m_jumpHopMaxTime.
void Character::setJumpHopMaxTimePositive ()
increments the time that the jump force is applied to the character
Definition at line 419 of file Character.cpp.
References m_jumpHopMaxTime.
void Character::setMassNegative ()
decrements the mass of the character
Definition at line 385 of file Character.cpp.
References m_mass.
void Character::setMassPositive ()
increment the mass of the character
Definition at line 380 of file Character.cpp.
References m_mass.
void Character::setMaxVelNegative ()
decrements the max velocity of the character
Definition at line 395 of file Character.cpp.
References m_maxVelocity.
void Character::setMaxVelPositive ()
increments the max velocity of the character
Definition at line 390 of file Character.cpp.
References m_maxVelocity.
void Character::setMultiplierNegative ()
decrements the multiplier of the velocity of the character
Definition at line 405 of file Character.cpp.
References m_mulitplier.
void Character::setMultiplierPositive ()
increments the multiplier of the velocity of the character
Definition at line 400 of file Character.cpp.
References m_mulitplier.
void Character::setShiftable (bool _canShift) inline
enable/disable the characters ability to shapeshift
Definition at line 110 of file Character.h.
References m_shiftable.
void Character::shapeshift ()
method to change the character from ball to leged and back
Definition at line 48 of file Character.cpp.
References PhysicsWorld::addLegSphere(), PhysicsWorld::addSphere(), PhysicsWorld::getAngVelocity(), PhysicsWorld::getLinVelocity(), PhysicsWorld::getPosition(), m_formOne, m_formTwo, m_mass, m_physics, m_shapeshift, m_shiftable, PhysicsWorld::removeCollisionObj(), PhysicsWorld::setAngVelocity(), and PhysicsWorld::setLinVelocity().
void Character::speed (std::string _shape)
increases the character velocity
Parameters
[in] _shape the character to affect the velocity increase
Definition at line 277 of file Character.cpp.
References PhysicsWorld::getLinVelocity(), m_physics, and PhysicsWorld::setLinVelocity().
void Character::startJumpHopTimer ()
starts the timer for the hop
Definition at line 238 of file Character.cpp.
References detectCollisionForJump(), jumpHopTimer, m_doubleJump, and LTimer::start().
void Character::stopJumpHopTimer ()
stop the timer for the hop
Definition at line 251 of file Character.cpp.
References jumpHopTimer, and LTimer::stop().
Member Data Documentation
LTimer Character::jumpHopTimer private
timer for the amount of time that the space bar is pressed during the characters jump
Definition at line 279 of file Character.h.
bool Character::m_attractEnable private
enables or disables the stickiness (attraction force)
Definition at line 263 of file Character.h.
ngl::Vec4 Character::m_cameraDir private
camera direction vector
Definition at line 243 of file Character.h.
ngl::Vec3 Character::m_charPos private
character position
Definition at line 255 of file Character.h.
bool Character::m_clamp private
disable or enable the velocity clamp
Definition at line 315 of file Character.h.
ngl::Vec3 Character::m_collisionNormal private
the normal of the collision check
Definition at line 251 of file Character.h.
bool Character::m_doubleJump private
the state of the character's double jump
Definition at line 295 of file Character.h.
std::string Character::m_formOne private
character in form one name
Definition at line 271 of file Character.h.
std::string Character::m_formTwo private
character in form two name
Definition at line 275 of file Character.h.
LTimer Character::m_freezeTimer private
the length of the freeze for the character
Definition at line 267 of file Character.h.
float Character::m_friction private
the friction of the character
Definition at line 291 of file Character.h.
ngl::Vec3 Character::m_initialBallPos private
initial position of the ball character
Definition at line 311 of file Character.h.
float Character::m_jumpForce private
the jumping impulse force
Definition at line 283 of file Character.h.
int Character::m_jumpHopMaxTime private
the maximum time that the jump force can be applied during a single jump
Definition at line 287 of file Character.h.
float Character::m_jumpHopTime private
the time that the character is jumping for
Definition at line 299 of file Character.h.
float Character::m_mass private
the mass of the character
Definition at line 235 of file Character.h.
float Character::m_maxVelocity private
the maximum velocity variable
Definition at line 239 of file Character.h.
ngl::Vec3 Character::m_move private
the movement direction vector of the character
Definition at line 259 of file Character.h.
float Character::m_mulitplier private
the velocity multiplier
Definition at line 231 of file Character.h.
ngl::Vec3 Character::m_oldPlatformVelocity private
the velocity of the platform from the previous frame
Definition at line 303 of file Character.h.
PhysicsWorld* Character::m_physics private
holds the pointer to the physics world
Definition at line 247 of file Character.h.
ngl::Vec3 Character::m_platformVelocity private
the velocity of the current frame of the platform
Definition at line 307 of file Character.h.
bool Character::m_shapeshift private
character phase (form)
Definition at line 319 of file Character.h.
bool Character::m_shiftable private
controls if character can shapeshift or not
Definition at line 227 of file Character.h.
The documentation for this class was generated from the following files:
Character.h
Character.cpp