LARRY_GAME: TriggerFactory Class Reference
TriggerFactory Class Reference
This class manages the trigger volumes, which are volumes that check collisions with the physics objects (character, platform etc.)
#include <TriggerFactory.h>
Public Member Functions
TriggerFactory (PhysicsWorld *_physics)
ctor for TriggerFactory class
void createTrigger (std::string _id, ngl::Vec3 _pointOne, ngl::Vec3 _pointTwo)
this is called in order to create a trigger volume
void deleteTrigger (std::string _id)
this is called in order to remove the trigger volume from the list
void readTriggerPosData ()
reads trigger volume position data from a txt file
void createTriggerFromFile ()
creates trigger volumes using the position data from the read file
void printTriggerList ()
prints a list of trigger volumes
bool checkPairHit (std::string _id, std::string _physicsObjName)
checks collision between a trigger object and a trigger volume returning a true if collision occurs and false if not
ngl::Transformation getTransform (std::string _id)
gets a ngl::transformation of trigger with the given _id name
ngl::Transformation getTransform (int _index)
gets a ngl::transformation of trigger with the given index from the list
int getTriggerListSize ()
gets the trigger volume list size
Private Attributes
PhysicsWorld * m_physics
a pointer used to hold the physics world pointer to acces the physics world of the game
std::vector< std::shared_ptr
< Trigger > > m_triggerList
used to hold the list of shared pointer of trigger volumes
std::vector< std::string > m_triggerListUnordered
a string list that is populated when a txt file is read with trigger volume positions
Detailed Description
This class manages the trigger volumes, which are volumes that check collisions with the physics objects (character, platform etc.)
Definition at line 17 of file TriggerFactory.h.
Constructor & Destructor Documentation
TriggerFactory::TriggerFactory (PhysicsWorld * _physics)
ctor for TriggerFactory class
Parameters
[in] _physics A pointer to the game physics world
Definition at line 3 of file TriggerFactory.cpp.
References m_physics.
Member Function Documentation
bool TriggerFactory::checkPairHit (std::string _id, std::string _physicsObjName)
checks collision between a trigger object and a trigger volume returning a true if collision occurs and false if not
Parameters
[in] _id a name of the trigger volume to check collision with
[in] _physicsObjName a name of the physics object in the physics world to check collision with
Definition at line 119 of file TriggerFactory.cpp.
References m_triggerList.
void TriggerFactory::createTrigger (std::string _id, ngl::Vec3 _pointOne, ngl::Vec3 _pointTwo)
this is called in order to create a trigger volume
Parameters
[in] _id a name of the trigger volume to create
[in] _pointOne a position of either min/max point of the trigger volume
[in] _pointTwo a position of either min/max point of the trigger volume
Definition at line 8 of file TriggerFactory.cpp.
References m_physics, and m_triggerList.
void TriggerFactory::createTriggerFromFile ()
creates trigger volumes using the position data from the read file
Definition at line 15 of file TriggerFactory.cpp.
References createTrigger(), and m_triggerListUnordered.
void TriggerFactory::deleteTrigger (std::string _id)
this is called in order to remove the trigger volume from the list
Parameters
[in] _id a name of the trigger volume to delete
Definition at line 29 of file TriggerFactory.cpp.
References m_triggerList.
ngl::Transformation TriggerFactory::getTransform (std::string _id)
gets a ngl::transformation of trigger with the given _id name
Parameters
[in] _id a name of the trigger volume to get the transformation of
Definition at line 74 of file TriggerFactory.cpp.
References m_triggerList.
ngl::Transformation TriggerFactory::getTransform (int _index)
gets a ngl::transformation of trigger with the given index from the list
Parameters
[in] _index of the trigger volume in the list
Definition at line 97 of file TriggerFactory.cpp.
References getTriggerListSize(), and m_triggerList.
int TriggerFactory::getTriggerListSize () inline
gets the trigger volume list size
Definition at line 68 of file TriggerFactory.h.
References m_triggerList.
void TriggerFactory::printTriggerList ()
prints a list of trigger volumes
Definition at line 109 of file TriggerFactory.cpp.
References m_triggerList.
void TriggerFactory::readTriggerPosData ()
reads trigger volume position data from a txt file
Definition at line 53 of file TriggerFactory.cpp.
References exit(), and m_triggerListUnordered.
Member Data Documentation
PhysicsWorld* TriggerFactory::m_physics private
a pointer used to hold the physics world pointer to acces the physics world of the game
Definition at line 74 of file TriggerFactory.h.
std::vector<std::shared_ptr<Trigger> > TriggerFactory::m_triggerList private
used to hold the list of shared pointer of trigger volumes
Definition at line 78 of file TriggerFactory.h.
std::vector<std::string> TriggerFactory::m_triggerListUnordered private
a string list that is populated when a txt file is read with trigger volume positions
Definition at line 82 of file TriggerFactory.h.
The documentation for this class was generated from the following files:
TriggerFactory.h
TriggerFactory.cpp