LARRY_GAME: main.cpp File Reference
main.cpp File Reference
#include <SDL.h>
#include <cstdlib>
#include <iostream>
#include <ngl/NGLInit.h>
#include <ngl/NGLStream.h>
#include "Ltimer.h"
#include "Controls.h"
#include "NGLDraw.h"
#include "Animation.h"
#include "GUIDraw.h"
#include "Text.h"
#include <boost/scoped_ptr.hpp>
Functions
void SDLErrorExit (const std::string &_msg)
function to quit SDL with error message
SDL_GLContext createOpenGLContext (SDL_Window *window)
initialize SDL OpenGL context
void openingCredits (GUIDraw *_gui)
void openingCutscene (GUIDraw *_gui)
void titleScreen (GUIDraw *_gui)
void mainMenu (GUIDraw *_gui)
void controlsScreen (GUIDraw *_gui)
void game (GUIDraw *_gui, Controls *_ctrl, Animation *m_animation, Character *_character, PhysicsWorld *_physics)
void pauseMenu (GUIDraw *_gui, Controls *_ctrl)
void exit (GUIDraw *_gui)
int main (int argc, char **argv)
Variables
boost::scoped_ptr< NGLDraw > nglScene
SDL_Window * window
LTimer fpsTimer
int countedFrames
LTimer capTimer
LTimer animTimer
LTimer idleTimer
bool spaceBarPressed
ngl::Vec3 move
bool debugValue
float m_time
int cutsceneTime
LTimer titleScreenTimer
LTimer fadeTimer
LTimer cutsceneTimer
bool showTitleScreenText
bool gamePaused
std::string gameState
bool quit
SDL_Event event
std::string formOne
std::string formTwo
bool characterStopped
Function Documentation
void controlsScreen (GUIDraw * _gui)
Definition at line 429 of file main.cpp.
References GUIDraw::drawControlsScreen(), event, gameState, nglScene, quit, LTimer::reset(), LTimer::stop(), and window.
SDL_GLContext createOpenGLContext (SDL_Window * window)
initialize SDL OpenGL context
Definition at line 813 of file main.cpp.
void exit (GUIDraw * _gui)
Definition at line 757 of file main.cpp.
References GUIDraw::drawExitScreen(), event, gameState, nglScene, quit, and window.
void game (GUIDraw * _gui, Controls * _ctrl, Animation * m_animation, Character * _character, PhysicsWorld * _physics)
Definition at line 463 of file main.cpp.
References CHAR_TYPE, Controls::characterMovement(), characterStopped, COIN_TYPE, countedFrames, debugValue, Character::detectCollisionForJump(), GUIDraw::drawMenuOpenBottom(), GUIDraw::drawMenuOpenTop(), event, formTwo, gamePaused, gameState, Animation::getAnimUpdate(), Controls::getJumpHopTime(), PhysicsWorld::getLinVelocity(), Character::getPhase(), Character::getPlatformVelocity(), LTimer::getTicks(), Animation::incrCurrentFrame(), Animation::initStartFrame(), JUMP, m_time, move, nglScene, quit, REST, REST2, Animation::setAnimationLoopOn(), Animation::setAnimationTo(), Animation::setAnimUpdate(), Controls::shapeshift(), spaceBarPressed, LTimer::start(), Controls::startJumpHopTimer(), Controls::stopJumpHopTimer(), WALK, and window.
int main (int argc, char ** argv)
Definition at line 55 of file main.cpp.
References characterStopped, controlsScreen(), countedFrames, createOpenGLContext(), cutsceneTime, debugValue, exit(), formOne, formTwo, game(), gamePaused, gameState, m_time, mainMenu(), move, nglScene, openingCredits(), openingCutscene(), pauseMenu(), quit, SDLErrorExit(), showTitleScreenText, spaceBarPressed, LTimer::start(), titleScreen(), and window.
void mainMenu (GUIDraw * _gui)
Definition at line 338 of file main.cpp.
References GUIDraw::drawMainMenu(), GUIDraw::drawMenuOpenBottom(), GUIDraw::drawMenuOpenTop(), GUIDraw::drawQuadColour(), event, gameState, LTimer::getTicks(), nglScene, quit, LTimer::start(), and window.
void openingCredits (GUIDraw * _gui)
Definition at line 169 of file main.cpp.
References GUIDraw::drawOpeningCredits(), GUIDraw::drawQuadColour(), event, gameState, LTimer::getTicks(), GUIDraw::loadAllTextures(), GUIDraw::loadTexture(), nglScene, quit, LTimer::start(), and window.
void openingCutscene (GUIDraw * _gui)
Definition at line 220 of file main.cpp.
References cutsceneTime, GUIDraw::drawOpeningCutscene(), GUIDraw::drawQuadColour(), event, gameState, LTimer::getTicks(), nglScene, quit, LTimer::start(), and window.
void pauseMenu (GUIDraw * _gui, Controls * _ctrl)
Definition at line 673 of file main.cpp.
References GUIDraw::drawPauseScreen(), GUIDraw::drawQuadColour(), event, gamePaused, gameState, move, nglScene, quit, spaceBarPressed, Controls::stopJumpHopTimer(), and window.
void SDLErrorExit (const std::string & _msg)
function to quit SDL with error message
Parameters
[in] _msg the error message to send
Definition at line 847 of file main.cpp.
References exit().
void titleScreen (GUIDraw * _gui)
Definition at line 262 of file main.cpp.
References cutsceneTime, GUIDraw::drawOpeningTitleSequence(), GUIDraw::drawQuadColour(), GUIDraw::drawTitleScreen(), GUIDraw::drawTitleScreenNoText(), event, gameState, LTimer::getTicks(), nglScene, quit, showTitleScreenText, LTimer::start(), and window.
Variable Documentation
LTimer animTimer
Definition at line 36 of file main.cpp.
LTimer capTimer
Definition at line 35 of file main.cpp.
bool characterStopped
Definition at line 53 of file main.cpp.
int countedFrames
Definition at line 34 of file main.cpp.
int cutsceneTime
Definition at line 42 of file main.cpp.
LTimer cutsceneTimer
Definition at line 45 of file main.cpp.
bool debugValue
Definition at line 40 of file main.cpp.
SDL_Event event
Definition at line 50 of file main.cpp.
LTimer fadeTimer
Definition at line 44 of file main.cpp.
std::string formOne
Definition at line 51 of file main.cpp.
std::string formTwo
Definition at line 52 of file main.cpp.
LTimer fpsTimer
Definition at line 33 of file main.cpp.
bool gamePaused
Definition at line 47 of file main.cpp.
std::string gameState
Definition at line 48 of file main.cpp.
LTimer idleTimer
Definition at line 37 of file main.cpp.
float m_time
Definition at line 41 of file main.cpp.
ngl::Vec3 move
Definition at line 39 of file main.cpp.
boost::scoped_ptr<NGLDraw> nglScene
Definition at line 22 of file main.cpp.
bool quit
Definition at line 49 of file main.cpp.
bool showTitleScreenText
Definition at line 46 of file main.cpp.
bool spaceBarPressed
Definition at line 38 of file main.cpp.
LTimer titleScreenTimer
Definition at line 43 of file main.cpp.
SDL_Window* window
Definition at line 32 of file main.cpp.